poppingmoon/aria

.github/workflows/build.yml
Renamed release.yml to build.yml and add workflow_dispatch to trigger.
When triggered, upload archives as artifacts and attach to release if tagged.
=> ci: make it possible to run build action on workflow_dispatch

lib/view/page/post_page.dart
Switching TextEditControllers of a MfmKeyboard leads to RangeError.
When building buttons, TagType from previous controller is keep preserved, so it tries to substring text to get query and accesses invalid range.
Fix this by simply using two MfmKeyboards, one for cw and the other for main text.
=> fix: avoid sharing MfmKeyboard among multiple TextEditControllers

lib/view/dialog/reaction_confirmation_dialog.dart, lib/view/widget/emoji_sheet.dart, lib/view/widget/follow_button.dart, lib/view/widget/note_footer.dart, lib/view/widget/reaction_button.dart
Show avatars of users as on top of the confirmation dialog to clearify from which account the user is acting.
| Follow | React |
| ---- | ---- |
| ![](https://github.com/poppingmoon/aria/assets/63451158/70575f3b-1ad1-4912-b9bb-1c77d721d5e8) | ![](https://github.com/poppingmoon/aria/assets/63451158/59f7f4d6-d0f7-4b63-aaeb-2bcaf65207d0) |
=> feat: show user avatars on confirm

lib/view/page/note_page.dart
Add a button to actions of `NotePage`.
Calls `notes/show` to get a fresh note on tap.
=> feat: add reload button to NotePage

lib/view/page/drive_page.dart, lib/view/page/image_page.dart, lib/view/page/settings/profile_page.dart, lib/view/widget/drive_create_sheet.dart, lib/view/widget/file_picker_sheet.dart
Add `type` property to `FilePickerSheet`, which controlls pickable file type.
For iOS, pass `FileType.media` to `FilePicker.platform.pickFiles()` by default.
This is because if `type` is `FileType.any`, iOS opens "Files" app, which is inconvenient for basic usage.
With `FileType.media`, it opens "Photos" app, where users can find their images and videos.
Close #54
=> feat: make it possible to filter files by type

lib/view/page/post_page.dart
In `PostPage`, `account` is a hook, so it should not be used directly.
=> fix: use `account.value` for push location

lib/view/dialog/antenna_settings_dialog.dart, lib/view/page/settings/tab_settings_page.dart
For tab and antenna, users can select a target user to track notes. Change these to also allow the user themselves to be a target user.
=> fix: allow selecting self for tab and antenna user

lib/view/widget/notification_widget.dart
When `renote` or `renoteGrouped` notifications are tapped, navigate to `NotePage` for renotes, not original notes.
=> fix: open renote on tap renote notification

lib/main.dart, lib/provider/audio_handler_provider.dart, lib/provider/audio_handler_provider.g.dart, lib/view/dialog/audio_dialog.dart
Initialize `AudioService` when `AudioDialog` is first loaded. This change shortens app's initialization duration.
=> perf: lazily initialize `AudioService`

lib/view/page/settings/tabs_page.dart
Add space to the end of tab list to avoid the last item from being
overlapped by the floating action button.
Fix #56
=> fix: add space to the bottom of `TabsPage`

lib/view/page/server/server_page.dart
Add copy button to end drawer of `ServerPage` so that users can copy the host of the server.
=> feat: add copy to server drawer

lib/provider/api/announcements_notifier_provider.dart, lib/provider/api/announcements_notifier_provider.g.dart
In Misskey, `announcements` has a parameter `untilId`, but io fork doesn't have `untilId` and instead has `offset`.
To make pagination work for both software, use both parameters.
https://github.com/misskey-dev/misskey/blob/6bd78770de06bd3694127da17ccd051f05057329/packages/backend/src/server/api/endpoints/announcements.ts#L35
https://github.com/MisskeyIO/misskey/blob/432833747d09f393b9c7451a73659600b081aab6/packages/backend/src/server/api/endpoints/announcements.ts#L30
=> fix: use `untilId` for announcements pagination

lib/view/widget/reaction_button.dart
Add border to `ReactionButton` if reactioned emoji is custom emoji, emoji with the same name exists locally and the user can react the local emoji.
ref: https://github.com/hideki0403/kakurega.app/commit/11d1e6354e5c56a77cbc5c86ff80397e1e2fcc8e
=> feat: add border to remote reaction if the emoji exists locally

lib/view/widget/emoji_sheet.dart, lib/view/widget/reaction_button.dart
When reacting from remote emoji, extract name from emoji and use local emoji with the same name instead of remote emoji itself.
=> fix: use local emoji with the same name for reaction fallback

lib/view/widget/url_preview.dart, lib/view/widget/url_widget.dart
If failed to parse url, display the input as it is.
=> fix: add fallback for invalid url to `UrlWidget`

lib/view/page/note_page.dart
=> fix: ignore trailing segment of remote renote url

lib/provider/streaming/incoming_message_provider.dart, lib/provider/streaming/incoming_message_provider.g.dart, lib/provider/streaming/web_socket_channel_provider.dart, lib/provider/streaming/web_socket_channel_provider.g.dart
Removed `keepAlive` from `incomingMessage` to avoid duplicate message
on rebuild of `TimelineStreamNotifier`.
=> fix: automatically dispose `incomingMessage`

lib/view/page/user/user_page.dart
`users/featured-notes` returns empty list for remote users, so the tab should be hidden.
ref: https://github.com/misskey-dev/misskey/blob/f9aed8f2bf994902386878d1212912caa3a57b0d/packages/backend/src/core/NoteCreateService.ts#L760-L763
=> fix: hide featured tab of remote users

lib/view/widget/notifications_list_view.dart, lib/view/widget/timeline_list_view.dart, lib/view/widget/timeline_widget.dart
When the last viewed date divider is on the widget tree, scroll to that widget with `Scrollable.ensureVisible()` instead of changing `centerId`.
=> feat: scroll to last viewed date if already built

lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_footer.dart, lib/view/widget/note_sheet.dart, lib/view/widget/note_widget.dart
In `NoteSheet`, unrenote button was not visible because of inappropriate judgments of conditions.
Fixed this by supplying an id of `note` instead of `appearNote`.
=> fix: show unrenote button

lib/provider/api/timeline_notes_notifier_provider.dart, lib/provider/api/timeline_notes_notifier_provider.g.dart, lib/view/widget/timeline_list_view.dart, lib/view/widget/timeline_widget.dart
Changed scroll behavior of when the "last viewed at" banner is tapped.
- If the divider is already built (or inside the screen), jump to it.
- Change from #113: removed animations because `Scrollable.ensureVisible()` also scrolls in a horizontal direction and makes unintended movements.
- If the oldest note in `TimelineNotesNotifier` is older than the last viewed date, repeatedly scroll for small offsets to find the divider.
- Otherwise, change the `centerId` and jump to the date.
We want to avoid the third case because fetching notes created after a date sometimes requires multiple requests.
So increased the number of notes fetched on build to make it more likely to be caught in the second case.
=> feat: scroll to last viewed date if older notes have been fetched

lib/provider/theme_data_provider.dart, lib/provider/theme_data_provider.g.dart
If `fontFamilyFallback` is set, Flutter will use the fallback fonts instead of the default device fonts.
https://api.flutter.dev/flutter/painting/TextStyle/fontFamilyFallback.html
=> fix: remove font family fallback if font is not set

lib/provider/accounts_notifier_provider.dart, lib/provider/accounts_notifier_provider.g.dart, lib/provider/categorized_emojis_provider.dart, lib/provider/categorized_emojis_provider.g.dart, lib/provider/custom_emoji_index_provider.dart, lib/provider/custom_emoji_index_provider.g.dart, lib/provider/emoji_provider.dart, lib/provider/emoji_provider.g.dart, lib/provider/emojis_notifier_provider.dart, lib/provider/emojis_notifier_provider.g.dart, lib/util/navigate.dart, lib/util/open_as_guest.dart, lib/view/dialog/icon_select_dialog.dart, lib/view/page/note_page.dart, lib/view/page/server/server_emojis.dart, lib/view/page/timelines_page.dart, lib/view/widget/emoji_sheet.dart, lib/view/widget/note_sheet.dart, lib/view/widget/reaction_button.dart, lib/view/widget/timeline_widget.dart
Moved the storage of emojis from shared preferences to files managed by the cache manager.
This reduces the size of shared preferences and will shorten the initialization duration of the app.
=> refactor: use cache manager to cache emojis

lib/view/widget/note_footer.dart
Wrapped `NoteFooter` with `FittedBox` to avoid overflow.
`NoteFooter` can contain up to 8 buttons for now, which makes it wider than the content of the note.
Despite this change, it will still overflow if a large scale is provided.
=> fix: scale `NoteFooter` to fit on notes

lib/view/page/search/search_notes.dart, lib/view/page/search/search_users.dart, lib/view/widget/misskey_server_autocomplete.dart
If a `focusNode` is provided, `TextField` will not give up focus if tapped outside.
This can Interrupt users, especially if they are using a software keyboard without a "close keyboard" button.
=> fix: explicitly call unfocus

lib/provider/api/attaches_notifier_provider.dart, lib/provider/api/attaches_notifier_provider.g.dart, lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart, lib/provider/pinned_emojis_notifier_provider.dart, lib/provider/pinned_emojis_notifier_provider.g.dart, lib/view/widget/pinned_emojis_editor.dart
Disabled tooltips of emojis in `PinnedEmojiEditor`, which prevent long press events from being caught by `ReorderableWrapper`.
Also fixed reorder logic to match with the difference of arguments between `ReorderableListView` and `ReorderableWrapper` or `ReorderableGridView`.
=> fix: reorder pinned emojis

lib/view/widget/mfm.dart, lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_simple_widget.dart, lib/view/widget/note_sub_widget.dart, lib/view/widget/note_summary.dart, lib/view/widget/note_widget.dart, lib/view/widget/sub_note_content.dart, lib/view/widget/translated_note_sheet.dart
Disabled nyaize for user descriptions by changing the default nyaize setting to disabled, which follows the setting of the `Mfm` component of Misskey Web.
=> fix: disable nyaize by default

lib/provider/api/endpoints_provider.dart, lib/provider/api/endpoints_provider.g.dart, lib/provider/api/notifications_notifier_provider.dart, lib/provider/api/notifications_notifier_provider.g.dart
If `useGroupedNotifications` is enabled and the server doesn't have `i/notifications-grouped` endpoint, create grouped notifications from response from `i/notifications`.
=> fix: fold notifications on the client side

lib/view/widget/notification_widget.dart
For the text of grouped notifications, use the number of unique users to show the correct number of users even if some users are reacting or renoting to a note repeatedly.
ref: `https://github.com/misskey-dev/misskey/pull/13751`
=> fix: show actual number of users for grouped notifications

lib/view/page/settings/note_display_page.dart
Add a missing switch for `showQuoteButtonInNoteFooter` setting.
=> fix: add quote button setting to appearance page

lib/view/widget/image_widget.dart
Changed to use `SvgPicture` only if the image url before `?` ends with `.svg`.
For example, an image url `https://example.tld/image.svg` can be converted to `https://example.tld/proxy/preview.webp?url=https://example.tld/image.svg` with a media proxy.
The proxied url directs to a webp image file, so it should not be parsed as a svg image.
=> fix: use svg if path part of the url ends with .svg

lib/view/widget/mention_widget.dart, lib/view/widget/mfm.dart
When a mention in a remote note to a user in the same server is tapped, open the user page of the remote server.
=> fix: open remote users page on tap mention

lib/view/widget/note_widget.dart
Changed to collapse renotes if targeted notes are long.
=> fix: collapse renoted long notes

lib/view/widget/timeline_list_view.dart
Supply `TimelineNote` with `ValueKey` of the note id.
This change will prevent the issue where when the index of a note in `TimelineListView` changes, statuses like the note is muted are applied to the adjacent note.
=> fix: use key to prevent reuse of note state

lib/view/widget/note_sheet.dart, lib/view/widget/timeline_menu.dart, lib/view/widget/timeline_widget.dart
Removed use of `if (i != null)` for a condition of showing buttons and replaced with `if (!account.isGuest)`.
These checks are meant to hide unusable buttons for guest users and `i` can be `null` even if `token` is available due to server conditions.
ref: #151
=> fix: replace unnecessary null check for i

lib/view/widget/note_sheet.dart, lib/view/widget/user_sheet.dart
Wrapped api calls in `onTap` callbacks in `NoteSheet` and `UserSheet` with `futureWithDialog()`.
=> fix: catch error for api call by user

lib/view/widget/timeline_header.dart
To avoid the header from being displayed in three lines, always show acct in one line.
=> fix: show acct in one line in `TimelineHeader`

lib/provider/theme_data_provider.dart, lib/provider/theme_data_provider.g.dart
When using `PredictiveBackPageTransitionsBuilder`, after pushing another page and popping back to `TimelinesPage`, `PostForm` loses the focus and will never get focused again.
Maybe related to `https://github.com/flutter/flutter/issues/148573`.
=> fix: disable intra-app predictive back

lib/provider/tokens_notifier_provider.dart, lib/provider/tokens_notifier_provider.g.dart
If the secure storage throws an error when loading a token, return null for the account.
=> fix: skip if failed to load token

lib/view/widget/notifications_list_view.dart, lib/view/widget/timeline_drawer.dart, lib/view/widget/timeline_menu.dart
When opening a notifications tab, set `hasUnreadNotification` to `true` and hide the badge on the notifications icon.
=> fix: mark notifications as read when open

lib/view/widget/note_detailed_widget.dart
In `NodeDetailedWidget`, added a margin on top of replies to add more
space around action buttons.
=> fix: add space between note and replies

lib/view/dialog/confirmation_dialog.dart, lib/view/dialog/error_message_dialog.dart, lib/view/dialog/message_dialog.dart, lib/view/dialog/post_confirmation_dialog.dart, lib/view/dialog/reaction_confirmation_dialog.dart
Added autofocus to confirmation buttons of dialogs to make it easy to proceed by　pressing the enter key on the keyboard.
=> fix: press enter to confirm

lib/view/page/channel/channel_home.dart, lib/view/page/post_page.dart, lib/view/page/settings/accounts_page.dart, lib/view/page/settings/tab_settings_page.dart, lib/view/page/settings/theme_manage_page.dart
Added space on the bottom of the pages that has floating action buttons with labels to prevent the contents from being overwrapped by the buttons.
Fix #182
=> fix: add space on pages with extended FABs

lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart, lib/provider/streaming/timeline_stream_notifier.dart, lib/provider/streaming/timeline_stream_notifier.g.dart
When a note from a streaming channel is received, yield it only if `NotesNotifier` does not have a note with its id.
This prevents notes on timelines from being duplicated.
=> fix: check if notes from stream are already stored

lib/provider/api/mutings_notifier_provider.dart, lib/provider/api/mutings_notifier_provider.g.dart
In `MutedUsersPage`, call `mute/delete` instead of `blocking/delete` when a delete button for the muted user is tapped.
=> fix: use correct endpoint to unmute

lib/view/widget/emoji_sheet.dart
When the "Copy" button in `EmojiSheet` is tapped, copy the name with the trailing `@.` removed.
=> fix: remove host when coping local emoji

lib/view/widget/notifications_list_view.dart, lib/view/widget/timeline_list_view.dart, lib/view/widget/timeline_widget.dart
Changed scroll physics of timelines on the main page to `ClampingScrollPhysics`.
With `BouncingScrollPhysics` of iOS, the tab header gets hidden after triggering pull-to-refresh.
=> fix: change scroll physics to clamping

pubspec.yaml
* change scroll physics to clamping ([#193](https://github.com/poppingmoon/aria/issues/193)) ([0d32a54](https://github.com/poppingmoon/aria/commit/0d32a543cb364bde6ca961cffe9953fbb724534f))
* remove host when copying local emoji ([#192](https://github.com/poppingmoon/aria/issues/192)) ([593fbfc](https://github.com/poppingmoon/aria/commit/593fbfcfcfdc61a566972fac784df90b6a2ea1ba))
* use correct endpoint to unmute ([#191](https://github.com/poppingmoon/aria/issues/191)) ([2323d51](https://github.com/poppingmoon/aria/commit/2323d515cc2c0d132e203277548fe3feac8b135a))
=> release: 0.9.5

lib/view/page/settings/profile_page.dart, lib/view/widget/file_picker_sheet.dart
Fixed the argument of `FileSystem.file()`.
Also changed to use cropped images when changing avatar or banner images.
=> fix: pick single file from device

lib/view/widget/mfm/search.dart
To avoid long queries from being displayed in multiple lines, wrapped the text with scroll view.
=> fix: make query of MFM search scrollable

lib/model/antenna_settings.dart, lib/model/antenna_settings.freezed.dart, lib/model/antenna_settings.g.dart, lib/provider/api/antennas_notifier_provider.dart, lib/provider/api/antennas_notifier_provider.g.dart, lib/view/dialog/antenna_dialog.dart, lib/view/dialog/antenna_settings_dialog.dart, lib/view/page/antenna_page.dart, lib/view/page/antennas_page.dart
Added a switch to set the `excludeBots` option for creating or updating antennas.
Also, we already had a `localOnly` switch, but its value was not used, so fixed to use it.
ref: `https://github.com/misskey-dev/misskey/pull/13603`
=> feat: support editing excludeBots option of antennas

lib/view/page/page/page_page.dart
Added placeholder for obsolete dynamic blocks of pages to indicate that the blocks were discontinued and no longer available.
ref: `https://github.com/misskey-dev/misskey/pull/13642`
=> feat: show placeholder for dynamic blocks of pages

lib/view/page/timelines_page.dart, lib/view/widget/post_form.dart
Added unique hero tags for each FABs in `TimelinesPage` to avoid the error `There are multiple heroes that share the same tag within a subtree.`
=> fix: add hero tags for FABs

lib/view/widget/note_sheet.dart
When the "Delete and edit" or "Delete" button in `NoteSheet` is selected, close the modal sheet first and then request delete.
This change avoids the `NO_SUCH_NOTE` error from blocking the instruction when at the `NotePage`.
=> fix: close `NoteSheet` before deleting the note

lib/view/widget/renote_sheet.dart
When "Renote" button of `RenoteSheet` is tapped and renote is done, pop the sheet to clarify that the interaction has succeeded.
=> fix: clear sheet on renote

lib/view/page/drive_page.dart
Changed `maxCrossAxisExtent` of grid items in `DrivePage` from 400 to 300 for better appearance in smaller devices.
=> fix: change max width of drive items

lib/view/widget/timeline_header.dart
Changed `TimelineHeader` to change its size only if the timeline is scrolling in a same direction for at least 3 frames continuously.
=> fix: suppress timeline header flickering

lib/extension/scroll_controller_extension.dart, lib/view/widget/follow_requests_list_view.dart, lib/view/widget/notifications_list_view.dart, lib/view/widget/timeline_list_view.dart
Changed to call `scrollToTop` twice when receiving a note from a stream.
The first call will be done 100 ms after the event, and the second call will be 100 ms after the first scroll is done.
This change makes timelines scroll to their exact top edge even though the size of notes changes over time while rendering emojis or images.
=> fix: scroll to top twice on receiving a note

lib/view/widget/mfm_keyboard.dart
Use `ListView` for displaying buttons of `MfmKeyboard` to lazily load emoji images.
May fix #216
=> fix: display keyboard buttons with ListView

lib/view/page/timelines_page.dart
The default animation for showing FAB rotates the button.
`TimelinesPage` uses a `Row` of buttons as FAB, so the animation rotates a wide widget, which is kind of confusing.
=> fix: disable rotation animation of fab

lib/view/widget/sub_note_content.dart
Removed padding around buttons in `SubNoteContent` to expand or collapse files or a poll.
=> fix: remove padding around collapsed files

lib/model/streaming/main_event.dart, lib/model/streaming/main_event.freezed.dart, lib/model/streaming/main_event.g.dart, lib/provider/api/drive_files_notifier_provider.dart, lib/provider/api/drive_files_notifier_provider.g.dart, lib/provider/streaming/main_stream_notifier_provider.dart, lib/provider/streaming/main_stream_notifier_provider.g.dart, lib/view/page/timelines_page.dart, lib/view/widget/drive_create_sheet.dart, lib/view/widget/file_picker_sheet.dart
Made it possible to attach a file to a note from its URL.
Misskey sends the file via the main streaming channel when the upload request is completed, but sometimes it does not appear on the stream.
To get the uploaded file in that case, request `drive/files/files` periodically and check if the file is already created.
Also added an option to upload a file to the drive from the URL.
Resolve #200
=> feat: upload from url

lib/view/widget/post_form_attaches.dart
Changed to hide the "Play video" button in `PostFormAttaches` if `video_player` is not supported for the platform.
=> fix: hide "Play video" button for unsupported platforms

lib/view/widget/note_widget.dart
Changed to display notes on panel color if background colors for them are not specified.
=> fix: use panel color for default note background color

lib/view/widget/mfm/code.dart
Wrapped `HighlightView` with `SingleChildScrollView` to make code blocks horizontally scrollable.
=> fix: make code block scrollable

lib/view/dialog/post_confirmation_dialog.dart, lib/view/widget/note_widget.dart
Changed to ignore specified background colors for notes in `PostConfirmationDialog`.
=> fix: disable background color of note in dialog

lib/view/widget/mfm/mfm_builder.dart
Changed alignment of `WidgetSpan` wrapping `Ruby` for a better appearance when texts with and without ruby are in the same line.
=> fix: align ruby above baseline

lib/view/widget/mfm/code.dart
Fixed `Code` not to expand horizontally if used as inline code.
=> fix: avoid expanding inline code

lib/provider/api/post_notifier_provider.dart, lib/provider/api/post_notifier_provider.g.dart, pubspec.lock, pubspec.yaml
Firefish requires the request for `notes/edit` to specify `visibility`.
https://firefish.dev/firefish/firefish/-/blob/78fdc56c3de4a2312504b55c487ad6d26f3065f2/packages/backend/src/server/api/endpoints/notes/edit.ts#L558
=> fix: fill all fields of `NotesEditRequest`

lib/view/dialog/image_gallery_dialog.dart
Added max height for image caption and made it scrollable so that it will not fill over the image.
=> fix: make image caption scrollable

lib/view/dialog/image_gallery_dialog.dart
Changed to disable the "swipe to dismiss" action while an image in `ImageGalleryDialog` is zoomed.
Fix #201
=> fix: disable dismiss gesture if zoomed

lib/view/widget/as_ui_widget.dart
Removed single line limitation of `helperText` in `AsUiWidget` to show complete captions for input fields.
=> fix: show long helper text on multiple lines

lib/view/dialog/delete_and_edit_dialog.dart, lib/view/widget/note_sheet.dart
Changed to use a new widget for delete and edit of the note.
The previous approach was to use the context of `NoteSheet` for showing indicators or routing.
The approach does not work well for some cases because the operation deletes the note `NoteSheet` is watching for, and the context is unmounted before pushing to the post page.
With this PR, adding `DeleteAndEditDialog`, a separate context is used during delete and edit so that the context will not be unmounted.
=> fix: add a dialog for delete and edit

lib/view/page/note_page.dart, lib/view/page/user/user_home.dart
Changed parent of buttons in remote user caution from `Row` to `Wrap` to display buttons horizontally if device width is wide enough, otherwise vertically.
=> fix: use wrap to display remote caution buttons

lib/view/page/about_aria_page.dart, lib/view/page/gallery/gallery_post_page.dart, lib/view/page/page/page_page.dart, lib/view/page/play/play_page.dart, lib/view/page/settings/languages_page.dart, lib/view/page/user/user_home.dart, lib/view/widget/bot_badge.dart, lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_header.dart, lib/view/widget/sub_note_content.dart
Applied `TextScaler.noScaling` for every `Text` in `WidgetSpan` for a better appearance with devices with a modified text scaler.
=> fix: disable text scaling inside WidgetSpan

lib/view/widget/note_detailed_widget.dart
Changed to omit children's area at the bottom of `NoteDetailedWidget` if the note has no replies or quotes.
This removes extra spaces with no meaning, which has a border on their left on iOS.
=> fix: hide children if the note has no children

lib/constant/fonts.dart, lib/view/widget/mfm/code.dart, lib/view/widget/mfm/mfm_builder.dart
Added Menlo to `fontFamilyFallback` of `Code`.
Related to #257
=> fix: add Menlo for fonts of code

pubspec.lock, pubspec.yaml
* add a dialog for delete and edit ([#252](https://github.com/poppingmoon/aria/issues/252)) ([7cb44e4](https://github.com/poppingmoon/aria/commit/7cb44e423a511dd1ae2c85be8c1cf37540e70f62))
* add Menlo for fonts of code ([#258](https://github.com/poppingmoon/aria/issues/258)) ([72a4a82](https://github.com/poppingmoon/aria/commit/72a4a82e30023bf4cce709db191947799783aba6))
* disable text scaling inside WidgetSpan ([#255](https://github.com/poppingmoon/aria/issues/255)) ([6a8d2ba](https://github.com/poppingmoon/aria/commit/6a8d2baa8a62e662df4e33871a6f194aaef454c0))
* hide children if the note has no children ([#256](https://github.com/poppingmoon/aria/issues/256)) ([d4171cb](https://github.com/poppingmoon/aria/commit/d4171cb5a445e3daf4559e678f38cb31302e254a))
* show icon for verified url …
=>  release: 0.10.2 

lib/model/mfm_config.dart, lib/model/mfm_config.freezed.dart, lib/view/widget/mfm.dart, lib/view/widget/mfm/blur.dart, lib/view/widget/mfm/mfm_builder.dart
Wrapped child of `[link]()` and `$[clickable]` with `AbsorbPointer` to capture gesture correctly even if tappable mfm like `:emoji:` is contained in it.
=> fix: prevent child of interactive mfm from being tapped 

lib/view/page/post_page.dart
Added clip behavior to `Card` to apply a circular border to the preview of the note even if a background color is specified.
=> fix: clip background of note preview

lib/view/widget/timeline_drawer.dart
Corrected the path to a user page when the response is a user.
=> fix: use id to open user page from lookup

lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart
This fixes an issue where polls contained in renotes are not visible.
ref: https://github.com/misskey-dev/misskey/blob/a6edd50a5d292e29e6292754a7be95205ac7dbc1/packages/backend/src/core/entities/NoteEntityService.ts#L371
=> fix: add renote as detailed at `NotesNotifier`

lib/view/dialog/delete_and_edit_dialog.dart
This fixes an issue where "delete and edit" does not complete if the target note is a reply.
=> fix: close dialog after deletion

lib/router/router.dart, lib/router/router.g.dart, lib/view/page/login_page.dart, lib/view/page/token_login_page.dart
When opening `TokenLoginPage` from `LoginPage`, send the host in the `TextField` to avoid re-entering it.
=> feat: use inputted host to open `TokenLoginPage`

lib/view/widget/play_widget.dart
Changed not to use the access token stored on Aria for `Mk:api` function inside Play to make the behavior compatible with Misskey Web.
ref: https://github.com/misskey-dev/misskey/blob/9ef6c4716ca25d8adeb5344c82a433370a086f88/packages/frontend/src/pages/flash/flash.vue#L190-L192
=> fix: do not pass token to Play

lib/provider/api/page_provider.dart, lib/provider/api/page_provider.g.dart, lib/provider/api/post_notifier_provider.dart, lib/provider/api/post_notifier_provider.g.dart, lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart, lib/view/dialog/post_confirmation_dialog.dart, lib/view/page/note_page.dart, lib/view/page/post_page.dart, lib/view/widget/note_fallback_widget.dart, lib/view/widget/note_summary.dart, lib/view/widget/post_form.dart, lib/view/widget/renote_sheet.dart
Fixed an issue where replies or renotes in drafts of notes are not visible in `PostForm` and `PostConfirmationDialog`.
=> fix: fetch reply and renote in draft

lib/view/widget/reactions_viewer.dart
Fixed an issue where reaction overlays continue to pop up after moving to another page.
=> fix: do not show reaction effect from previous page

lib/util/future_with_dialog.dart
This fixes an issue where `CircularIndicator` does not close when calling `futureWithDialog` multiple times.
=> fix: remove `OverlayEntry` even if not mounted

lib/view/widget/account_settings_navigation.dart, lib/view/widget/general_settings_navigation.dart
This fixes an issue where paddings are inserted below navigations in `SettingsPage` and `AccountSettingsPage` on iOS.
=> fix: remove padding of settings navigations

lib/util/open_as_guest.dart
On `futureWithDialog`, `PopupEntry` is closed after future is completed and `context.push()` completes when the new page is popped. So awaiting `context.push()` prevents the `PopupEntry` from being closed as expected.
=> fix: unawait push inside `futureWithDialog`

lib/view/page/settings/tab_settings_page.dart
This fixes an issue where `TabSettingsPage` does not close after tapping the delete button.
=> fix: unawait deleting tab

linux/my_application.cc, macos/Runner/Base.lproj/MainMenu.xib, macos/Runner/Configs/AppInfo.xcconfig, windows/runner/main.cpp
For Windows, macOS, and Linux, changed the app name displayed on the window from "aria" to "Aria".
=> chore: capitalize window title on desktop platforms

.github/workflows/build.yml
Split the job that builds APK and App Bundle into two jobs that build each.
Also, changed build number for App Bundle to make it compatible with the separated APKs.
=> ci: split Android build job

lib/view/page/settings/settings_page.dart
This fixes an issue where the texts of the navigation are not updated after updating ui language.
=> fix: remove const from `GeneralSettingsNavigation`

lib/provider/accounts_notifier_provider.dart, lib/provider/accounts_notifier_provider.g.dart, lib/view/page/authenticate_page.dart
Changed to save token before adding an account when signing in. This change prevents the `CREDENTIAL_REQUIRED` error if storing the token failed while signing in.
=> fix: do not add account if failed to save token

lib/view/widget/as_ui_widget.dart, lib/view/widget/custom_emoji.dart, lib/view/widget/image_widget.dart, lib/view/widget/mfm.dart
Disabled fade-in animations of emoji images in Plays because some of Plays updates their content quickly and emojis are not displayed if they are removed while fading-in.
=> fix: show emojis in Plays immediately

lib/provider/api/post_notifier_provider.dart, lib/provider/api/post_notifier_provider.g.dart, lib/provider/timeline_tab_index_notifier_provider.dart, lib/provider/timeline_tab_index_notifier_provider.g.dart, lib/provider/timeline_tab_settings_provider.dart, lib/provider/timeline_tab_settings_provider.g.dart, lib/view/page/post_page.dart, lib/view/page/timelines_page.dart, lib/view/widget/post_form.dart
With #69, the same channel is set to a new request after posting a note to a channel, but this behavior is confusing if the current tab is not a channel tab. This PR changes this behavior to only be effective if the tab is a channel tab.
=> fix: reset channel after post

README.md
Now Aria is available on [Google Play](https://play.google.com/store/apps/details?id=com.poppingmoon.aria), [App Store](https://apps.apple.com/app/aria-for-misskey/id6499410880) and [Snap Store](https://snapcraft.io/aria).
=> chore: add store links to README.md

pubspec.yaml
* edit target note of renote ([#319](https://github.com/poppingmoon/aria/issues/319)) ([20393fa](https://github.com/poppingmoon/aria/commit/20393fa3e82dcfc4ef3512cca8c926143ef40a0d))
=> release: 0.13.6

lib/view/page/timelines_page.dart
This fixes an issue where tab settings do not update when swiping from right to left.
=> fix: always update tab index

lib/view/widget/note_sheet.dart
Changed to use `appearNote.id` instead of `noteId` in `NoteSheet` to deal with renoted notes properly.
=> fix: handle appearNote in NoteSheet

lib/view/page/settings/privacy_page.dart
Wrapped reaction acceptances with tuples to identify null as accept all.
=> fix: allow default reaction acceptance to be null

lib/model/account_settings.dart, lib/model/account_settings.freezed.dart, lib/model/account_settings.g.dart, lib/provider/account_settings_notifier_provider.dart, lib/provider/account_settings_notifier_provider.g.dart, lib/view/page/settings/privacy_page.dart, lib/view/widget/renote_sheet.dart
Changed to remember the visibility of renotes separately from the visibility of normal notes.
Resolve #332
=> feat: remember renote visibility

lib/view/page/clips_page.dart, lib/view/page/gallery/gallery_my.dart, lib/view/page/play/plays_my.dart, lib/view/widget/clip_preview.dart, lib/view/widget/gallery_post_preview.dart, lib/view/widget/play_preview.dart
Removed user avatars from previews of clips, gallery posts, and Plays when listing those created by the user.
ref: `https://github.com/misskey-dev/misskey/pull/14256`
=> feat: hide user info from previews in "my-" tab

lib/view/page/timelines_page.dart
When changing timeline tabs, compare tabs using [`TabController.previousIndex`](https://api.flutter.dev/flutter/material/TabController/previousIndex.html) instead of the value of `timelineTabIndexNotifierProvider` because the provider value does not update inside the callback function.
Fix #329
=> fix: use previousIndex for comparing tabs

lib/view/widget/timeline_widget.dart
Changed the icon at the top of `TimelineWidget` that appears when newer notes exist from `Icons.history` to `Icons.update`.
=> chore: change icon of scroll to new banner

lib/view/widget/image_widget.dart, lib/view/widget/media_card.dart
This is a temporary workaround for an issue where clipping is not working for Impeller in Flutter 3.24.0 (`https://github.com/flutter/flutter/issues/153118`).
=> fix: remove colorFilter for Impeller

lib/extension/text_editing_controller_extension.dart
This fixes an issue where inputted text gets overwritten after inserting text from `MfmKeyboard` when using Japanese IME.
=> fix: clear composing range when inserting text

lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart
Suppress incrementing reaction count when adding a reaction if the cached note has already been updated via streaming event.
=> fix: increment reaction count if cache is not updated

pubspec.yaml
* increment reaction count if cache is not updated ([#371](https://github.com/poppingmoon/aria/issues/371)) ([5b80865](https://github.com/poppingmoon/aria/commit/5b8086505f1ef6f1fbcce8d853b6e904b67e4700))      
* open MiAuth in app if iOS ([#369](https://github.com/poppingmoon/aria/issues/369)) ([31db8c1](https://github.com/poppingmoon/aria/commit/31db8c166928c89a8cd1dff5fb71e131daffa219))
=> release: 0.14.4

lib/view/widget/mfm_keyboard.dart
Fixed an issue where `MfmKeyboard` shows no buttons after an invalid argument of mfm function.
=> fix: show default keyboard if fnArgs is empty

lib/provider/emoji_url_provider.dart, lib/provider/emoji_url_provider.g.dart
Extract the original image url if the supplied emoji url is already proxied.
Fixes an issue where remote emojis do not render on some servers.
=> fix: extract original url from proxied url

lib/view/page/user/user_notes.dart
Removed `firstDate` parameter for the time machine in `UserNotes` since notes can be older than the user if imported from another account.
=> fix: remove first date constraint for time machine

crowdin.yml
Changed paths in crowdin.yml to absolute.
=> build: fix path of translated files

lib/view/page/post_page.dart
Added keys for `NoteWidget` used for preview in the post page. 
Using different keys prevents widgets from being reused when switching between quote and renote.
Fix #392
=> fix: add keys to note preview

lib/provider/accounts_notifier_provider.dart, lib/provider/accounts_notifier_provider.g.dart
Changed to convert the list of accounts to a set when adding an account.
Fix #393
=> fix: do not allow duplicate account

lib/provider/api/notifications_notifier_provider.dart, lib/provider/api/notifications_notifier_provider.g.dart
If a notification with the same id as the specified `untilId` exists in the fetched notifications, remove it.
Fix #395
=> fix: remove duplicate notification

lib/view/widget/pinned_emojis_editor.dart
This fixes an issue where general pinned emojis do not reset when tapping the reset button.
=> fix: reset pinned emojis

lib/view/widget/notification_widget.dart
Changed the size of the user icons in grouped notifications to comply with the avatar scale setting.
=> fix: apply avatar scale to grouped notifications

.github/workflows/ci.yml
On the branch Crowdin pushes translated files to, ci actions always fail because files generated by slang will not update.
=> ci: ignore l10n-main branch

lib/provider/api/timeline_notes_after_note_notifier_provider.dart, lib/provider/api/timeline_notes_after_note_notifier_provider.g.dart, lib/provider/notes_notifier_provider.dart, lib/provider/notes_notifier_provider.g.dart, lib/provider/streaming/timeline_stream_notifier.dart, lib/provider/streaming/timeline_stream_notifier.g.dart
Removed check for the cached note inside `TimelineStreamNotifier`. This was intended to avoid duplicate notes for streaming, but since posting notes also caches them, this was causing the notes posted by the user not to appear in the timelines.
The duplicate notes will now be checked during the `TimelineNotesAfterNoteNotifier.addNote` method.
Fix #336
=> fix: check duplicate notes per timelines

lib/view/page/emoji_page.dart
Fixed an issue where the `localOnly` field in the `EmojiPage` is showing the `isSensitive` flag instead.
=> fix: show local only in emoji page

lib/view/page/about_aria_page.dart
Added build number in the `AboutAriaPage`.
For Android, release builds will add a digit to the build number specified in pubspec.yaml, so remove the last digit when displaying the number.
=> feat: show build number

lib/provider/api/timeline_notes_after_note_notifier_provider.dart, lib/provider/api/timeline_notes_after_note_notifier_provider.g.dart
Fixed an issue where the duplicate check added in #418 was comparing the newly received note with the oldest note in the timeline while it should be compared with the newest note.
=> fix: compare new note with the first note

lib/view/widget/emoji_picker.dart
When opening an emoji picker in a modal bottom sheet, if the setting for automatically focusing the search field is enabled, expand the sheet to 80% to the top.
This makes search results to be less hidden by the software keyboard.
=> feat: expand emoji picker if auto focus is enabled

lib/main.dart
When showing push notifications, remove colons and the host part from reactions.
=> fix: show reaction name in notification

lib/view/widget/note_footer.dart, lib/view/widget/note_sheet.dart, lib/view/widget/translated_note_sheet.dart
Changed to allow `TranslatedNoteSheet` to occupy at most 80% of the screen height.
=> feat: expand translated note sheet

lib/view/page/user/user_home.dart, lib/view/widget/custom_emoji.dart, lib/view/widget/emoji_sheet.dart, lib/view/widget/mfm.dart
Fixed an issue where emojis on the cw text and other widgets cannot detect tap.
=> fix: use onTapEmoji in Mfm widget

lib/view/widget/note_footer.dart, lib/view/widget/reaction_button.dart, lib/view/widget/reaction_users_sheet.dart, test/view/widget/note_footer_test.dart, test_util/create_container.dart, test_util/create_overrides.dart, test_util/dummy_note.dart
Added a horizontal bar on top of the `ReactionUsersSheet` so that the user can see users who added another reaction without closing the sheet.
=> feat: show all reactions in ReactionUsersSheet

lib/provider/message_opened_app_notifier_provider.dart, lib/provider/message_opened_app_notifier_provider.g.dart
Changed to mark notifications as read when a push notification is tapped in order to hide the dot indicator on the notification icon.
=> feat: mark notifications as read on tap

lib/view/page/settings/languages_page.dart
Fixed an issue where all language names are displayed as "English" after lazy loading of translations was introduced in [slang 4.0.0](https://pub.dev/packages/slang/changelog#400).
=> fix: load locales when opening languages page

lib/provider/post_notifier_provider.dart, lib/provider/post_notifier_provider.g.dart
Removed unnecessary update process which was called when `TextEditingController` was updated.
Fix #457
=> fix: avoid updating PostNotifier state if text is not changed

lib/view/widget/post_form.dart
Changed to not show the warning for mentions if the note is not a reply to another note.
=> fix: hide extra mentions warning if not reply

lib/view/widget/post_form.dart
#375 was intended to work only when pasting a url, but `Uri.tryParse()` actually parses a text without a scheme, making normal text wrapped in a link syntax. This PR fixes the problem by checking if the parsed url has an http or https scheme.
=> fix: check scheme when pasting a link

lib/extension/notes_create_request_extension.dart, lib/model/account_settings.dart, lib/model/account_settings.freezed.dart, lib/model/account_settings.g.dart, lib/provider/account_settings_notifier_provider.dart, lib/provider/post_form_hashtags_notifier_provider.dart, lib/provider/post_form_hashtags_notifier_provider.g.dart, lib/provider/post_notifier_provider.dart, lib/provider/post_notifier_provider.g.dart, lib/provider/theme_data_provider.dart, lib/provider/theme_data_provider.g.dart, lib/view/page/post_page.dart, lib/view/page/tag/tag_page.dart, lib/view/widget/mention_widget.dart, lib/view/widget/mfm_keyboard.dart, lib/view/widget/post_form.dart, test/view/widget/mfm_keyboard_test.dart, test_util/dummy_user_detailed_not_me.dart, test_util/dummy_user_lite.dart
Added a text field for additional hashtags to the post form.
The tags will be kept for the next post.
=> feat: preserve hashtags in post form

lib/view/page/drive_page.dart
When selecting a destination folder for file movement, the drive page is in the state of some files selected and selecting a folder at the same time. This conflict is causing undesired behavior when tapping the close icon at the top left. Also, it makes the page title wrong. This PR fixes these issues.
=> fix: dismiss drive file move on pop

lib/view/widget/mfm.dart
Fixed an issue where the style is not applied to unicode emojis in MFM after #445.
Fix #463
=> fix: apply text style for unicode emoji

lib/view/widget/note_summary.dart
Changed to remove the content text for the summary of the note if a content warning is attached to it.
=> fix: hide content from summary if cw is provided

lib/view/page/drive_page.dart, lib/view/widget/drive_folder_sheet.dart, lib/view/widget/paginated_list_view.dart
Applied `AlwaysScrollableScrollPhysics` to `PagenatedListView` to make pull-to-refresh work even if the list has no elements.
=> fix: always make pull-to-refresh triggerable

.github/workflows/ci.yml
iPhone 14 was removed from available devices.
ref: https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-latest/_compare/1ba16ab52702384ef1769863d8e0580f79e7e18c...8d67e209458b6eb7d777d1a9942d72f3f3cf7903
=> ci: use iPhone 15 for integration test

lib/view/page/page/page_page.dart
Fixed an issue where children of page sections do not have paddings.
=> fix: add paddings around children of page sections

lib/view/page/tag/tag_page.dart
Set `postFormUseHashtags` to true when the "Post to this hashtag" button is tapped.
Fix #479
=> fix: open hashtags form when post to hashtag

lib/view/page/timelines_page.dart
Fixed an issue where the timelines page crashes when there are less than 5 buttons at the bottom.
=> fix: replace sublist with take

lib/view/dialog/user_select_dialog.dart, lib/view/widget/mfm_keyboard.dart, test/view/widget/mfm_keyboard_test.dart
Fixed an issue where keyboards do not appear if there is a text before the opening tag.
=> fix: change query for mfm keyboard

lib/view/widget/announcement_widget.dart, lib/view/widget/cw_button.dart, lib/view/widget/note_widget.dart, lib/view/widget/sub_note_content.dart
Fixed an issue where the CW button looks too small on desktop platforms.
Follow up for #482
=> fix: use fixed visual density for cw button

lib/view/page/timelines_page.dart, lib/view/widget/timeline_header.dart, lib/view/widget/timeline_tab_bar.dart
Reduced label padding of the tabs in the timeline tab bar to make them square.
=> fix: change timeline tabs to be square

lib/view/widget/instance_ticker_widget.dart
When a remote note does not contain the server's name, display its host instead in the instance ticker.
=> fix: show host in instance ticker as a fallback

lib/view/page/login_page.dart, lib/view/page/token_login_page.dart, lib/view/widget/misskey_server_autocomplete.dart
Added a check for MiAuth support before login. If the server does not support MiAuth, redirect to the token login page.
=> feat: login with token if MiAuth is not supported

lib/view/widget/misskey_server_background.dart
If the server does not provide a background image, use a banner or icon image instead for the background of the login page.
=> fix: add fallbacks for the server background images

lib/view/widget/custom_emoji.dart
Fixed an issue where emoji mute for remote emojis does not work for emojis in the notes.
=> fix: use host for emoji mute

lib/view/widget/player_embed.dart, lib/view/widget/twitter_embed.dart, lib/view/widget/url_preview.dart
Enabled embed of players and tweets for Windows since `flutter_inappwebview` has added support for the platform in [6.1.0](https://pub.dev/packages/flutter_inappwebview/changelog#610).
Currently, a tap event on a web view propagates to the widgets below on Windows. To prevent other widgets from being tapped, the web view is wrapped with an InkWell with an empty `onTap` handler.
=> feat: enable embed for Windows

lib/constant/misskey_web_push_proxy_url.dart
Changed `misskeyWebPushProxyUrl` to point to a proxy running on Cloudflare Workers. 
ref: https://github.com/poppingmoon/misskey-web-push-proxy/tree/cloudflare-workers
=> chore: change url of web push proxy

lib/view/widget/mfm_keyboard.dart, test/view/widget/mfm_keyboard_test.dart
Fixed an issue where the emoji keyboard does not appear if the cursor is after a colon adjacent to an emoji code.
=> fix: show emoji keyboard for colon next to emoji

lib/main.dart
Fixed an issue where push notifications are sometimes not localized on Android.
=> fix: set locale before showing notification

lib/provider/emoji_url_provider.dart, lib/provider/emoji_url_provider.g.dart, lib/provider/proxied_image_url_provider.dart, lib/provider/proxied_image_url_provider.g.dart, lib/provider/static_image_url_provider.dart, lib/provider/static_image_url_provider.g.dart, lib/view/widget/instance_ticker_widget.dart
Added `proxiedImageUrlProvider` to remove duplicate process for getting proxied images.
=> refactor: organize media proxy

lib/view/widget/mfm.dart
Added [`Unicode.FSI`](https://api.flutter.dev/flutter/foundation/Unicode/FSI-constant.html) at the start and [`Unicode.PDI`](https://api.flutter.dev/flutter/foundation/Unicode/PDI-constant.html) and the end of MFM spans.
This prevents directional characters inside an MFM from affecting surrounding texts.
=> fix: wrap MFM with bidirectional isolate

lib/view/widget/media_card.dart
Fixed an issue where double tap and long press events are ignored by `MediaCard` and caught by the parent `NoteWidget`.
=> fix: open image on double tap or long press

lib/view/dialog/image_dialog.dart, lib/view/dialog/image_gallery_dialog.dart
Added feature to close `ImageGalleryDialog` by tapping outside of the image.
When the image is tapped, the overlay buttons will be hidden. 
Fix #415
=> feat: dismiss image on tap outside

.github/workflows/ci.yml
Replaced `fail_error` key of `reviewdog/action-suggester` action with `fail_level`.
=> ci: replace deprecated option of reviewdog/action-suggester

.github/workflows/build.yml
Changed the build job for Linux arm64 to run the same job as x64 but on the newly added arm runner.
Previously, the job used Docker running on QEMU, which resulted in longer build times. With the arm runner, the build time is significantly reduced.
ref: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview
=> ci: use arm runner to build for Linux arm64

lib/view/widget/post_form.dart
Fixed an issue where the text field for annotations is focused when opening a post form if the reply target note has cw.
With this change, the annotations field will not be autofocused and will instead focus on the main text field.
=> fix: remove autofocus from cw text field

lib/view/widget/drive_folder_sheet.dart, lib/view/widget/url_sheet.dart
Changed the height of dividers between the header and the content of sheets to zero.
=> fix: remove height of sheet headers

lib/view/page/settings/mute_block_page.dart, lib/view/widget/muted_words_editor.dart
Changed to use [`LineSplitter`](https://api.dart.dev/dart-convert/LineSplitter-class.html) instead of `text.split('\n')`.
=> fix: use LineSplitter to split lines

lib/provider/proxied_image_url_provider.dart, lib/provider/proxied_image_url_provider.g.dart
Changed to add query parameters to the original url if it is from a media proxy.
=> fix: use original url if already proxied

.github/workflows/ci.yml
Instead of installing the default version of Dart, install Flutter with the version specified in `.fvmrc` when checking the format. 
This will avoid inconsistent formatting caused by different Dart versions introduced by FVM and the latest stable channel.
=> ci: install Flutter for format

lib/provider/api/clip_notes_notifier_provider.dart, lib/provider/api/clip_notes_notifier_provider.g.dart, lib/provider/api/clips_notifier_provider.dart, lib/provider/api/clips_notifier_provider.g.dart, lib/provider/api/note_clips_notifier_provider.dart, lib/provider/api/note_clips_notifier_provider.g.dart, lib/util/get_note_action.dart, lib/view/dialog/clip_dialog.dart, lib/view/page/clip_page.dart, lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_footer.dart, lib/view/widget/note_sheet.dart, lib/view/widget/note_widget.dart
Changed to show the unclip button in the note sheet when the sheet was opened from the clip page.
This fixes an issue where users cannot remove a note from a clip when the clip has reached the notes limit.
=> feat: add unclip button to note sheet

lib/view/widget/media_card.dart, lib/view/widget/media_list.dart
Changed the layout of images in notes.
This prevents having empty space at the bottom right when 3 files are attached to a note.
| Before | After |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/20cdb4dc-8e20-44fc-88b1-f833361e8efd) | ![image](https://github.com/user-attachments/assets/f0319885-ceff-48a2-a1d6-40a97ffc991d) |
=> feat: change layout of MediaList with 3 files

lib/view/dialog/image_dialog.dart, lib/view/dialog/image_gallery_dialog.dart, lib/view/dialog/video_dialog.dart
Fixed an issue where the size of the menu button and the close button is different in `ImageDialog`, `ImageGalleryDialog`, and `VideoDialog`.
=> fix: remove Material around PopupMenuButton

lib/view/dialog/image_dialog.dart, lib/view/dialog/image_gallery_dialog.dart, lib/view/page/timelines_page.dart
Fixed an issue where `ImageGalleryDialog` flickers during loading because the thumbnail url was passed to the `blurHash` parameter of `ImageDialog` used in `loadingBuilder`.
Follow up for #518
=> fix: remove BlurHash from loading image 

lib/view/widget/notifications_list_view.dart, lib/view/widget/timeline_list_view.dart, lib/view/widget/timeline_note.dart
Changed to hide a new note if it is a duplicate of a previous note.
=> fix: hide duplicate notes from streaming

lib/util/compress_image.dart
Fixed an issue where heic files are not compressed in Aria 1.0.1, possibly due to the update of file_picker.
=> fix: compress heic

lib/view/widget/note_detailed_widget.dart
Fixed an issue where replies and quotes do not appear if the note page is opened from a renote notification.
=> fix: use appearNote to get children notes

lib/view/page/antennas_page.dart, lib/view/page/channel/channels_favorites.dart, lib/view/page/channel/channels_featured.dart, lib/view/page/clips_page.dart, lib/view/page/explore/explore_roles.dart, lib/view/page/gallery/gallery_popular.dart, lib/view/page/list/lists_page.dart, lib/view/page/page/pages_featured.dart, lib/view/page/server/server_ads.dart, lib/view/page/server/server_emojis.dart, lib/view/page/user/user_lists.dart
Wrapped labels for empty lists with `SingleChildScrollView` to enable pull-to-refresh.
ref: #473
=> fix: enable pull-to-refresh when list is empty

android/app/src/main/AndroidManifest.xml
ref: https://developer.android.com/privacy-and-security/risks/access-control-to-exported-components
Fix #606
=> fix: do not export AudioService

lib/view/widget/timeline_widget.dart
Fixed an issue where dialog-style announcements cannot be scrolled when they are long.
ref: `https://github.com/misskey-dev/misskey/pull/15878`
=> fix: enable scrolling for announcement dialog

lib/view/page/note_page.dart, lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_sub_widget.dart
Changed the behavior of the reload button on the note page to also reload its parent and children notes.
=> fix: reload children notes

lib/provider/api/drive_files_notifier_provider.dart, lib/provider/api/drive_files_notifier_provider.g.dart, lib/provider/api/drive_folders_notifier_provider.dart, lib/provider/api/drive_folders_notifier_provider.g.dart, lib/view/page/drive_page.dart, lib/view/widget/drive_file_info.dart
Added a space to the bottom of the drive page to make items at the bottom not be covered by the FAB.
=> fix: add space to the bottom of drive page

lib/main.dart
Changed to show an error dialog when registration for UnifiedPush failed.
The dialog will show [`FailedReason`](https://pub.dev/documentation/unifiedpush/latest/unifiedpush/FailedReason.html).
Related to #608
=> feat: show reason when UnifiedPush registration failed

lib/model/mfm_config.dart, lib/model/mfm_config.freezed.dart, lib/view/widget/custom_emoji.dart, lib/view/widget/mfm.dart, lib/view/widget/unicode_emoji.dart, pubspec.lock, pubspec.yaml
Changed scale of nested `$[x2`, `$[x3`, `$[x4` functions.
The outermost function has the normal effect, the second one has about half the effect, and the rest have no effect.
ref: `https://github.com/misskey-dev/misskey/issues/7445#issuecomment-2851275850`
ref: https://github.com/misskey-dev/misskey/blob/2025.5.0/packages/frontend/src/style.scss#L641-L653
Related to #470
=> fix: limit scale of nested x* mfm functions

lib/extension/image_extension.dart, lib/model/layer.dart, lib/model/layer.freezed.dart, lib/view/page/image_page.dart, lib/view/widget/layers_sheet.dart, lib/view/widget/layers_viewer.dart, pubspec.lock, pubspec.yaml
Removed use of `image_size_getter` in the `ImagePage` and get size from [`Image`](https://api.flutter.dev/flutter/dart-ui/Image-class.html) instead.
This prevents UI crash caused by errors from `image_size_getter` not being handled correctly.
=> refactor: remove image_size_getter

lib/view/widget/mfm/code.dart
Changed to remove the final newline in code blocks to avoid displaying an extra empty line.
=> fix: ignore final newline in code block

lib/util/compress_image.dart
Changed to return a compressed image from `compressImage()` if the input is heic/heif because those formats are not rendered on the app and the browser.
For the other formats, the function returns compressed one only if the image size was reduced after resizing.
=> fix: always use converted image if input is heic

integration_test/play_test.dart, lib/view/dialog/account_select_dialog.dart, lib/view/dialog/antenna_settings_dialog.dart, lib/view/dialog/avatar_decoration_dialog.dart, lib/view/dialog/chat_message_send_confirmation_dialog.dart, lib/view/dialog/clip_settings_dialog.dart, lib/view/dialog/confirmation_dialog.dart, lib/view/dialog/delete_and_edit_dialog.dart, lib/view/dialog/duration_picker_dialog.dart, lib/view/dialog/field_dialog.dart, lib/view/dialog/file_caption_edit_dialog.dart, lib/view/dialog/list_settings_dialog.dart, lib/view/dialog/message_dialog.dart, lib/view/dialog/mute_dialog.dart, lib/view/dialog/post_confirmation_dialog.dart, lib/view/dialog/reaction_confirmation_dialog.dart, lib/view/dialog/text_field_dialog.dart, lib/view/page/avatar_decorations_page.dart, lib/view/widget/follow_button.dart, lib/view/widget/play_widget.dart
Changed the cancel buttons of dialogs to `ElevatedButton` and made the background color different from the dialog color.
Also added icons to some dialogs without a title.
| Before | After |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/83afb1cf-9305-47d6-996e-0339136987e2) | ![image](https://github.com/user-attachments/assets/2906cfd2-4dbb-4a7a-9453-d9b54a13ee5e) |
| ![image](https://github.com/user-attachments/assets/191d00ed-d0f0-49b4-91cd-511e660249af) | ![image](https://github.com/user-attachments/assets/bb514fa4-2421-494b-8b16-cd1f93ecf19a) |
=> fix: change background color of cancel button

lib/view/widget/mfm.dart, lib/view/widget/mfm/crop.dart
Added support for the `crop` function for MFM.
This function is from Firefish and is not supported in Misskey Web.
ref: https://codeberg.org/firefish/firefish/src/commit/02c31e0a2804de48c9d73028df525e197d8df622/packages/client/src/components/mfm.ts#L301-L316
Fix #635
=> feat: add crop function for MFM

lib/view/widget/emoji_sheet.dart
Corrected the icon of the "pin to emoji picker" button in `EmojiSheet`.
=> fix: change icon of pin emoji button

lib/provider/note_collapse_reason_provider.dart
Changed to collapse code blocks with a lot of newlines.
There is no option for `HighlightView` to limit the lines, so the whole block was displayed even if `maxLine` is specified for `Mfm`. With this change, if a code block has more newlines than the threshold, `Mfm` is clipped by height in the same manner as #623.
=> fix: collapse long code block

lib/view/page/login_page.dart
=> fix: correct parameter name for token login page

lib/view/dialog/image_gallery_dialog.dart, lib/view/page/gallery/gallery_post_page.dart
Fixed an issue where the text at the bottom of the `ImageGalleryDialog` is red when shown from the gallery posts page.
=> fix: wrap file comment with Material

lib/view/dialog/user_image_gallery_dialog.dart
Changed to exclude files other than images from `UserImageGalleryDialog`.
=> fix: filter image files in user image gallery dialog

lib/view/widget/notification_widget.dart
Changed to show the user name in one line in the `NotificationWidget`.
=> fix: truncate long user name in notification

lib/view/widget/as_ui_widget.dart
Fixed an issue where the `hidden` parameter of `Ui:C:Container` is ignored.
=> fix: correct pattern matching for container of AsUiComponent

lib/util/get_note_action.dart
Fixed an issue where an emoji picker opened from a note action displays the general emoji picker and shows a confirmation when a user taps an emoji.
=> fix: use emoji picker for reaction in note action

lib/view/page/user/user_page.dart
Corrected the tab length in `UserPage` when opened with acct.
=> fix: correct tab length in user page

lib/view/page/settings/behavior_page.dart
Disabled the predictive back option for older Android versions because [`PredictiveBackPageTransitionsBuilder`](https://api.flutter.dev/flutter/material/PredictiveBackPageTransitionsBuilder-class.html) is only effective for Android 14 and above.
=> fix: disable predictive back for Android 13 and older

lib/util/create_aiscript.dart, rust/src/api/aiscript/api.rs
Changed the `info` parameter of the error value returned by `Mk:api` to have the type object instead of a string.
=> fix: convert api error in AiScript to json

lib/util/get_note_action.dart, lib/view/widget/deleted_note_widget.dart, lib/view/widget/deleted_renote_widget.dart, lib/view/widget/muted_note_widget.dart, lib/view/widget/note_detailed_widget.dart, lib/view/widget/note_sheet.dart, lib/view/widget/note_simple_widget.dart, lib/view/widget/note_sub_widget.dart, lib/view/widget/note_widget.dart, lib/view/widget/renote_header.dart, lib/view/widget/timeline_note.dart, test/view/widget/note_widget_test.dart
Starting from Misskey 2025.8.0, renotes and replies whose target note has been deleted may still contain the target id. This PR adds support for those notes.
ref: [misskey-dev/misskey#16332](https://redirect.github.com/misskey-dev/misskey/pull/16332)
=> fix: show placeholder for deleted note

lib/view/widget/mfm.dart
Changed the `height` of fallback text for custom emojis to 1.0 to display the emoji code at the same level as the surrounding text.
=> fix: remove paddings around fallback text of custom emoji

lib/view/dialog/aiscript_dialog.dart
Fixed an issue where `AiScriptDialog` didn't show the full content when the title is long.
=> fix: make AiScriptDialog scrollable

android/app/build.gradle
Converted `android/app/build.gradle.kts` to `android/app/build.gradle` as a workaround because Flutter 3.35.3 modifies version codes when using Kotlin DSL.
ref: #716 
ref: [flutter/flutter#173917 (comment)](https://github.com/flutter/flutter/issues/173917#issuecomment-3258805949)
=> build: use build.gradle

lib/view/widget/chat_post_form.dart, test/view/widget/chat_post_form_test.dart
Fixed an issue where the text field in the chat post form did not open when tapped.
ref: [flutter/flutter#174652](https://redirect.github.com/flutter/flutter/issues/174652)
=> fix: maintain focusability for hidden text field

lib/view/dialog/paste_emojis_dialog.dart, lib/view/widget/pinned_emojis_editor.dart
Changed to show the emoji palette page in `PasteEmojisDialog` when `i/read-all-unread-notes` is missing.
Follow up for #603
=> fix: change condition to show emoji palette page

lib/view/dialog/message_dialog.dart, lib/view/page/settings/import_export_page.dart, lib/view/page/settings/theme_manage_page.dart
Changed the icon of the `MessageDialog` for non-error messages.
=> fix: change icon of message dialog

lib/view/dialog/sw_register_dialog.dart
Replaced a top-level return statement with a `Core:abort` function call in the script in `SwRegisterDialog` .
In AiScript 1.x, return statements outside a function are prohibited.
=> fix: use abort in sw/register script

lib/view/page/timelines_page.dart
Made the buttons at the bottom of the timelines page slightly transparent for better visibility.
=> fix: change opacity of timelines page buttons

lib/provider/pinned_emojis_notifier_provider.dart, lib/provider/pinned_emojis_notifier_provider.g.dart, lib/view/widget/custom_emoji.dart, lib/view/widget/emoji_picker.dart, lib/view/widget/pinned_emojis_editor.dart, lib/view/widget/unicode_emoji.dart
Enabled opening the emoji sheet by long-pressing an emoji in the emoji picker.
=> feat: open emoji sheet from emoji picker
