pubspec.lock
pubspec.yaml

Make LayersViewer to display WebP image correctly.

fix: use forked version of image_size_getter

---

lib/model/tab_settings.g.dart
lib/model/tab_type.dart
lib/provider/api/timeline_notes_after_note_notifier_provider.dart
lib/provider/api/timeline_notes_after_note_notifier_provider.g.dart
lib/provider/api/timeline_notes_notifier_provider.dart
lib/provider/api/timeline_notes_notifier_provider.g.dart
lib/provider/miauth_notifier_provider.g.dart
lib/router/router.g.dart
lib/view/page/settings/tab_settings_page.dart
lib/view/widget/follow_requests_list_view.dart
lib/view/widget/notifications_list_view.dart
lib/view/widget/tab_icon_widget.dart
lib/view/widget/tab_type_widget.dart
lib/view/widget/timeline_list_view.dart

Make it possible to show notifications as a tab.
If type of tab is `TabType.notifications`, `TimelineListView` redirects to `NotificationsListView`.

feat: add notifications tab

---

lib/i18n/misskeyIO/misskeyIO_en-US.i18n.yaml
lib/i18n/misskeyIO/misskeyIO_ja-JP.i18n.yaml
lib/i18n/misskeyIO/misskeyIO_ja-KS.i18n.yaml
lib/i18n/misskeyIO/misskeyIO_ko-GS.i18n.yaml
lib/i18n/misskeyIO/misskeyIO_ko-KR.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/i18n/strings_ja_JP.g.dart
lib/i18n/strings_ja_KS.g.dart
lib/i18n/strings_ko_GS.g.dart
lib/i18n/strings_ko_KR.g.dart
lib/provider/api/skeb_status_provider.dart
lib/provider/api/skeb_status_provider.g.dart
lib/view/page/user/user_home.dart
pubspec.lock
pubspec.yaml
test_util/dummy_me_detailed.dart

Show skeb status in UserHome.
ref: `https://github.com/MisskeyIO/misskey/pull/573`

feat: skeb status

---

.github/workflows/ci.yml
build.yaml
lib/i18n/misskeyIO/misskeyIO_ja-KS.i18n.yaml
lib/i18n/misskeyIO/misskeyIO_ko-GS.i18n.yaml
lib/provider/api/post_notifier_provider.g.dart
pubspec.lock
pubspec.yaml

Run `dart run build_runner build` and check that there is no diff.
Prevents pushing without updating generated files.

ci: add action to check if generated files is up to date

---

lib/view/widget/url_preview.dart

Show url as a title until summaly returns summary.

fix: fallback url preview

---

lib/view/dialog/account_select_dialog.dart
lib/view/page/explore/explore_users.dart
lib/view/widget/misskey_server_autocomplete.dart

Overwrite paste event on `MisskeyServerAutoComplete` and remove scheme part and text after first slash.

feat: trim host before paste

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/aria/aria_ja-JP.i18n.yaml
lib/i18n/aria/aria_ja-KS.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/i18n/strings_ja_JP.g.dart
lib/i18n/strings_ja_KS.g.dart
lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/view/dialog/icon_select_dialog.dart
lib/view/page/post_page.dart
lib/view/widget/emoji_picker.dart

Add option for keeping emoji picker open.
The option will only be shown if emoji picker is opened via emoji button in post page.

feat: enable inputting multiple emojis for post

---

pubspec.lock
pubspec.yaml

* add `NoteDisplayPage` ([#46](https://github.com/poppingmoon/aria/issues/46)) ([51bc084](https://github.com/poppingmoon/aria/commit/51bc084e546bcddabce098954454bf7ed7402c4b))
* add like button ([#49](https://github.com/poppingmoon/aria/issues/49)) ([23a9f98](https://github.com/poppingmoon/aria/commit/23a9f981204cf1fbb4cd2832f2ae508ac2ad4637))
* add reload button to NotePage ([#43](https://github.com/poppingmoon/aria/issues/43)) ([b33b577](https://github.com/poppingmoon/aria/commit/b33b5775e17ad51f5b6eb878273f659dc6d102b6))
* add server info to UserSheet ([#30](https://github.com/poppingmoon/aria/issues/30)) ([8c0d721](https://github.com/poppingmoon/aria/commit/8c0d72192c33c901eb5f46d5853cfe10c1a34381))
* add trailing icon to translate item if translator is unavailable …

release: 0.4.0

---

lib/view/page/settings/import_export_page.dart

When importing from drive, sort files named 'aria.json' or 'aria.json.unknown' by `createdAt` and use the latest file for import.

fix: import the latest backup file in a folder

---

lib/view/widget/note_sub_widget.dart

Add vertical space between `NoteSubWidget`s.

fix: add padding to `NoteSubWidget`

---

lib/provider/api/drive_stats_provider.dart
lib/provider/api/drive_stats_provider.g.dart
lib/view/page/drive_page.dart
lib/view/page/settings/drive_settings_page.dart
lib/view/widget/drive_file_info.dart
lib/view/widget/media_card.dart
pubspec.lock
pubspec.yaml

Add a graph that displays usage and capacity of drive to `DriveSettingsPage`.
Also show usage amount in `DrivePage`.

feat: show drive usage

---

lib/provider/receive_sharing_intent_provider.dart
lib/provider/receive_sharing_intent_provider.g.dart
pubspec.lock
pubspec.yaml

* add copy to server drawer ([#67](https://github.com/poppingmoon/aria/issues/67)) ([4bd0b05](https://github.com/poppingmoon/aria/commit/4bd0b057a947053cc5038a8036aeb604ea08b2b5))
* install themes ([#71](https://github.com/poppingmoon/aria/issues/71)) ([5f570dc](https://github.com/poppingmoon/aria/commit/5f570dcf9dc70a0081a938b6e460ed347adbc480))
* make it possible to filter files by type ([#55](https://github.com/poppingmoon/aria/issues/55)) ([95c082b](https://github.com/poppingmoon/aria/commit/95c082b62928c4ff45006ec09c3dffaad012465f)), closes [#54](https://github.com/poppingmoon/aria/issues/54)
* post notes after files are uploaded ([#66](https://github.com/poppingmoon/aria/issues/66)) ([dc52fd5](https://github.com/poppingmoon/aria/commit/dc52fd5635a7777122a6112982e08ad10670b95b))
* …

release: 0.5.0

---

lib/extension/note_extension.dart
lib/extension/notes_create_request_extension.dart
lib/view/page/post_page.dart
lib/view/widget/cw_button.dart
lib/view/widget/post_form.dart

ref: `https://github.com/misskey-dev/misskey/pull/13670`

feat: allow text of reply or cw quote to be empty

---

lib/model/account_settings.dart
lib/model/account_settings.freezed.dart
lib/model/account_settings.g.dart
lib/provider/account_settings_notifier_provider.dart
lib/provider/account_settings_notifier_provider.g.dart
lib/provider/api/attaches_notifier_provider.dart
lib/provider/api/attaches_notifier_provider.g.dart
lib/provider/api/drive_files_notifier_provider.dart
lib/provider/api/drive_files_notifier_provider.g.dart
lib/util/randomize_filename.dart
lib/view/dialog/post_file_editor_dialog.dart
lib/view/page/settings/drive_settings_page.dart
lib/view/widget/drive_create_sheet.dart
lib/view/widget/drive_file_sheet.dart

Add an option to switch whether to keep the original filename on upload.
ref: `https://github.com/misskey-dev/misskey/pull/13688`
ref: `https://github.com/misskey-dev/misskey/pull/13699`

feat: randomize filename on upload

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/aria/aria_ja-JP.i18n.yaml
lib/i18n/aria/aria_ja-KS.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/i18n/strings_ja_JP.g.dart
lib/i18n/strings_ja_KS.g.dart
lib/router/router.dart
lib/router/router.g.dart
lib/view/page/about_aria_page.dart
lib/view/page/settings/settings_page.dart

Remove `AboutListTile` from `SettingsPage` and replace it with a new page.

feat: add `AboutAriaPage`

---

lib/model/tab_settings.dart
lib/model/tab_settings.freezed.dart
lib/model/tab_settings.g.dart
lib/provider/api/id_gen_method_provider.dart
lib/provider/api/id_gen_method_provider.g.dart
lib/provider/streaming/timeline_stream_notifier.dart
lib/provider/timeline_center_notifier_provider.dart
lib/provider/timeline_center_notifier_provider.g.dart
lib/provider/timeline_tabs_notifier_provider.dart
lib/provider/timeline_tabs_notifier_provider.g.dart
lib/router/router.dart
lib/router/router.g.dart
lib/view/page/settings/tab_settings_page.dart
lib/view/page/settings/tabs_page.dart
lib/view/page/user/user_notes.dart
lib/view/widget/timeline_list_view.dart
lib/view/widget/timeline_menu.dart

This allows users to jump to a certain point of the timelines.

feat: time machine

---

lib/router/router.dart
lib/router/router.g.dart
lib/view/page/settings/appearance_page.dart
lib/view/page/settings/emoji_picker_page.dart
lib/view/page/settings/pinned_emojis_editor_page.dart
lib/view/page/settings/settings_page.dart

Move emoji picker settings from `AppearancePage` to a new page.

feat: organize settings related to emoji picker

---

pubspec.yaml

release: 0.6.1

---

lib/view/page/user/user_featured.dart
lib/view/page/user/user_notes.dart
lib/view/page/user/user_page.dart

Change trigger of time machine from `ListTile` to `IconButton` to expand main content size of `UserNotes`.
Also moved featured notes to another tab to make `SegmentedButton` slim.

fix: change time machine of user page to icon

---

lib/view/dialog/clip_dialog.dart
lib/view/widget/error_message.dart
pubspec.lock
pubspec.yaml

Catch errors from Misskey API and show appropriate messages in `ErrorMessage`.

feat: show descriptions of errors

---

lib/extension/scroll_controller_extension.dart

ref: https://github.com/misskey-dev/misskey/blob/f9aed8f2bf994902386878d1212912caa3a57b0d/packages/frontend/src/components/MkPagination.vue#L500

fix: shorten timeline scroll duration

---

README.md

Now that Aria is available on F-Droid.
https://f-droid.org/packages/com.poppingmoon.aria

chore: add F-Droid link to README.md

---

lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/emoji_url_provider.dart
lib/provider/emoji_url_provider.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/provider/static_image_url_provider.dart
lib/provider/static_image_url_provider.g.dart
lib/view/page/settings/note_display_page.dart
lib/view/widget/instance_ticker.dart
lib/view/widget/instance_ticker_widget.dart
lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_widget.dart

- Added an option to change which kind of note shows the instance ticker.
- Changed to use proxied image URLs rather than original favicon URLs for user privacy.
- Reduced height of instance tickers so that they look closer to those of Misskey Web's.
Resolve #125

feat: change condition to show instance ticker

---

lib/provider/api/search_notes_notifier_provider.dart
lib/provider/api/search_notes_notifier_provider.g.dart
lib/view/page/search/search_notes.dart

Apply the local-only search setting to the search results.

fix: search local notes

---

lib/view/dialog/clip_dialog.dart
lib/view/widget/clip_preview.dart
pubspec.lock
pubspec.yaml

Show the number of notes in a clip for `ClipPreview` and `ClipDialog`.
ref: `https://github.com/misskey-dev/misskey/pull/13686`

feat: show number of notes in clips

---

lib/view/dialog/list_dialog.dart
lib/view/page/lists_page.dart

Show the number of users in a list for `ListDialog`.

feat: show number of users in list

---

lib/view/page/post_page.dart

Set the max width of the main part of `PostPage` to 800 for a better appearance on devices with wide screens.

fix: limit width of post page

---

lib/model/data_saver.dart
lib/model/data_saver.freezed.dart
lib/provider/data_saver_provider.dart
lib/provider/data_saver_provider.g.dart
lib/view/widget/avatar_decorations.dart
lib/view/widget/cat_avatar.dart
lib/view/widget/media_card.dart
lib/view/widget/mention_widget.dart
lib/view/widget/url_preview.dart
lib/view/widget/user_avatar.dart

The setting to disable data saver when on wifi was not applied to the avatar image animations.

 fix: apply data saver disabling to avatars 

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/aria/aria_ja-JP.i18n.yaml
lib/i18n/aria/aria_ja-KS.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/i18n/strings_ja_JP.g.dart
lib/i18n/strings_ja_KS.g.dart
lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/provider/theme_data_provider.dart
lib/provider/theme_data_provider.g.dart
lib/view/page/settings/note_display_page.dart

Added a slider to change the space between lines.

feat: make line height configurable

---

lib/view/widget/timeline_list_view.dart

fix: use correct index for next notes

---

.github/workflows/ci.yml

Read the flutter version from `.fvmrc` and use that version of flutter in ci jobs.

ci: use specific version of flutter

---

lib/provider/streaming/broadcast_provider.dart
lib/provider/streaming/broadcast_provider.g.dart
lib/provider/streaming/incoming_message_provider.dart
lib/provider/streaming/incoming_message_provider.g.dart
lib/provider/streaming/note_update_event_provider.dart
lib/provider/streaming/note_update_event_provider.g.dart
lib/provider/streaming/timeline_stream_notifier.dart
lib/provider/streaming/timeline_stream_notifier.g.dart

This change may fix an issue that the newest note from streaming duplicates when reloaded.

fix: better streaming handling

---

lib/view/page/settings/note_display_page.dart
pubspec.lock
pubspec.yaml

ref: https://pub.dev/packages/multi_split_view/changelog#310

refactor: use multi_split_view 3.1.0

---

pubspec.lock
pubspec.yaml

* add adaptive navigation for settings ([#127](https://github.com/poppingmoon/aria/issues/127)) ([8bb04eb](https://github.com/poppingmoon/aria/commit/8bb04ebc3e3da635384e1d66af99fe4ffa2443b9))  
* add header to clip page ([#140](https://github.com/poppingmoon/aria/issues/140)) ([2de3ee4](https://github.com/poppingmoon/aria/commit/2de3ee455814b08875937ceab9ae96e64079a5b7))
* cache meta and i ([#131](https://github.com/poppingmoon/aria/issues/131)) ([deed7b2](https://github.com/poppingmoon/aria/commit/deed7b2360e176c0c669d4db005e3fe525782c7e))
* change condition to show instance ticker ([#128](https://github.com/poppingmoon/aria/issues/128)) ([9ffe9b5](https://github.com/poppingmoon/aria/commit/9ffe9b5442a69dd33866ea6a7d25e59d8b5ecf9f))
* hide tab header on scroll down …

release: 0.8.0

---

.github/workflows/build.yml
ios/ExportOptions.plist
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
ios/Runner/Runner.entitlements

Added workflow to sign and publish IPA.

ci: publish IPA to TestFlight

---

pubspec.yaml

release: 0.8.1

---

lib/view/page/settings/import_export_page.dart

When the drive folder selected by a user doesn't contain a backup file, show a dialog to indicate that they are selecting the wrong folder.

fix: show message if backup file is not found

---

lib/view/widget/note_sheet.dart

fix: show unrenote only if renote

---

.github/workflows/build.yml
pubspec.yaml

* show unrenote only if renote ([#170](https://github.com/poppingmoon/aria/issues/170)) ([c411ffe](https://github.com/poppingmoon/aria/commit/c411ffe3fb208836abc746b9394c8f9e2fd3f136))
* "build: upgrade Flutter to 3.22.0 ([#163](https://github.com/poppingmoon/aria/issues/163))" ([#172](https://github.com/poppingmoon/aria/issues/172)) ([b9f2838](https://github.com/poppingmoon/aria/commit/b9f283888377d94289b32dec3e2209c44166b680))

release: 0.9.1

---

pubspec.yaml

release: 0.9.2

---

.github/workflows/build.yml
macos/Runner/Info.plist
pubspec.yaml

* add space between note and replies ([#176](https://github.com/poppingmoon/aria/issues/176)) ([6dccd92](https://github.com/poppingmoon/aria/commit/6dccd92d473c0b03a436486b293101c2c07e82ae))

 release: 0.9.3 

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/strings_en_US.g.dart

fix: add English translation of `newNotifications`

---

.github/workflows/ci.yml

Suggest changes in PRs if files generated on GitHub Actions are different from the committed files.

ci: suggest changes

---

lib/view/dialog/antenna_dialog.dart
lib/view/dialog/antenna_settings_dialog.dart
lib/view/page/antennas_page.dart

Added missing implementation for the callback of the create button of the `AntennaDialog`.
Also fixed the title of the dialog.

feat: create antenna on tap create button

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

* add FABs at the bottom of timelines ([#202](https://github.com/poppingmoon/aria/issues/202)) ([5fc87ea](https://github.com/poppingmoon/aria/commit/5fc87ea16fa579681d4ffa57a74032ce4ef832e1))
* create antenna on tap create button ([#203](https://github.com/poppingmoon/aria/issues/203)) ([7659ced](https://github.com/poppingmoon/aria/commit/7659ced04ef74af28d4ab4a73481541d92649564))
* Play ([#207](https://github.com/poppingmoon/aria/issues/207)) ([09f3688](https://github.com/poppingmoon/aria/commit/09f368835b38f686852a0166d27d041076b1f549))
* show placeholder for dynamic blocks of pages ([#206](https://github.com/poppingmoon/aria/issues/206)) ([320a940](https://github.com/poppingmoon/aria/commit/320a940d8edf0c3a4250de68e0c39d9030687628))
* support editing excludeBots option of antennas …

release: 0.10.0-beta.0

---

lib/view/widget/post_form.dart

Wrapped buttons at the bottom left of `PostForm` (files, poll, ...) with a scroll view to make all the buttons available even if the width of the device is small.

fix: make buttons of `PostForm` scrollable

---

lib/view/page/play/play_edit_page.dart
lib/view/widget/play_widget.dart

When showing remote Play, use a guest account to render MFM to show custom emojis.

fix: show Play summary as guest

---

lib/view/page/tag_page.dart

This PR adds "Post to hashtag" button.
Closes: #218

feat: Add "Post to hashtag" button

---

pubspec.yaml

* Add "Post to hashtag" button ([#222](https://github.com/poppingmoon/aria/issues/222)) ([af0e4c4](https://github.com/poppingmoon/aria/commit/af0e4c4f1b7143151a80e8c098ec067a00e402f3))
* change max width of drive items ([#220](https://github.com/poppingmoon/aria/issues/220)) ([c85a4aa](https://github.com/poppingmoon/aria/commit/c85a4aa13051cd34171c0a87cea1d8f23a39cee6))
* clear sheet on renote ([#219](https://github.com/poppingmoon/aria/issues/219)) ([de3bbf5](https://github.com/poppingmoon/aria/commit/de3bbf57fc64725bb7afdb869954499bb2bd484f))
* display keyboard buttons with ListView ([#225](https://github.com/poppingmoon/aria/issues/225)) ([d444e82](https://github.com/poppingmoon/aria/commit/d444e82c5ac2c51884eeb216e929d7eaccdf827b))
* scroll to top twice on receiving a note …

release: 0.10.0-beta.2

---

lib/extension/scroll_controller_extension.dart
lib/view/page/timelines_page.dart
lib/view/widget/mfm_keyboard.dart
lib/view/widget/post_form.dart
lib/view/widget/post_form_attaches.dart

- Fixed vertical padding of `MfmKeyboard` buttons
- Changed to use `Stack` to show `PostForm` on `TimelinesPage`
- Made the size of file thumbnails smaller for `PostForm` on `TimelinesPage`
- Removed gaps between buttons in `PostForm`
- Fixed issues on switching tabs while opening the form
Fix #216 
Fix #217

fix: show post form with stack

---

lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_widget.dart

Add space between note text and channel name.

fix: add padding above channel name in note

---

lib/view/widget/timeline_drawer.dart

Added a feature to open a page from url.
Resolve #209

feat: support lookup

---

lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/view/page/settings/note_display_page.dart
lib/view/widget/note_widget.dart

Added options to `NoteDisplayPage` to change the background colors of notes by their visibilities.

feat: make background color of notes configurable

---

lib/view/widget/mention_widget.dart
lib/view/widget/mfm_keyboard.dart

Removed margin around `ActionChip` in `MentionWidget`.
Fix #240

fix: remove margin around mention

---

.github/workflows/build.yml
macos/Podfile.lock
macos/Runner/Info.plist
pubspec.lock
pubspec.yaml

* align ruby above baseline ([#242](https://github.com/poppingmoon/aria/issues/242)) ([17f1c3f](https://github.com/poppingmoon/aria/commit/17f1c3fed6a880d6fb1c88601c6688bcc95c8d6f))
* avoid expanding inline code ([#244](https://github.com/poppingmoon/aria/issues/244)) ([3e048c4](https://github.com/poppingmoon/aria/commit/3e048c487d2d4db9bfe5f973362ffbc9b4b8efc4))
* disable background color of note in dialog ([#239](https://github.com/poppingmoon/aria/issues/239)) ([8364924](https://github.com/poppingmoon/aria/commit/83649247fd62fea229a0eca827f497deb3e7f810))
* make code block scrollable ([#238](https://github.com/poppingmoon/aria/issues/238)) ([0045f17](https://github.com/poppingmoon/aria/commit/0045f17b88f06a99d6099241d08f647bd36263a9))
* remove margin around mention …

release: 0.10.0

---

lib/gen/assets.gen.dart
pubspec.lock
pubspec.yaml

* disable dismiss gesture if zoomed ([#249](https://github.com/poppingmoon/aria/issues/249)) ([0ce0301](https://github.com/poppingmoon/aria/commit/0ce03017076ec747c9a25c8c937235be24ed711a))
* disable text scaling inside MFM ([#246](https://github.com/poppingmoon/aria/issues/246)) ([78acc01](https://github.com/poppingmoon/aria/commit/78acc016af3bbdbd238e9b1f5e0b54021918c07a))
* fill all fields of `NotesEditRequest` ([#247](https://github.com/poppingmoon/aria/issues/247)) ([93beee6](https://github.com/poppingmoon/aria/commit/93beee6d7bfbd45241f07c3f724cab4f63575b25))
* make image caption scrollable ([#248](https://github.com/poppingmoon/aria/issues/248)) ([d9caa9e](https://github.com/poppingmoon/aria/commit/d9caa9ef031d119f8ba858e9aedf09268eecd074))
* show long helper text on multiple lines …

release: 0.10.1

---

lib/view/page/settings/profile_page.dart
lib/view/page/user/user_home.dart
lib/view/widget/url_widget.dart

Changed to show icon at the end of the verified url in user profiles.

fix: show icon for verified url 

---

lib/view/page/user/user_home.dart

fix: compare month to calculate age

---

lib/provider/api/tag_users_provider.dart
lib/provider/api/tag_users_provider.g.dart
lib/router/router.dart
lib/router/router.g.dart
lib/view/page/explore/explore_users.dart
lib/view/page/tag/tag_notes.dart
lib/view/page/tag/tag_page.dart
lib/view/page/tag/tag_users.dart
lib/view/page/user/user_home.dart
lib/view/widget/mfm.dart
lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_widget.dart
lib/view/widget/paginated_list_view.dart
lib/view/widget/sub_note_content.dart
lib/view/widget/timeline_drawer.dart
lib/view/widget/user_info.dart
lib/view/widget/users_sort_type_widget.dart

Add a tab to show users with the hashtag in their profiles.

feat: add users tab to hashtag page

---

lib/view/widget/notifications_list_view.dart
lib/view/widget/timeline_list_view.dart
lib/view/widget/timeline_widget.dart

The problem mentioned in #193 seems to be fixed probably because of #223.

revert: "fix: change scroll physics to clamping (#193)"

---

pubspec.lock
pubspec.yaml

* add option to open url with internal browser ([#263](https://github.com/poppingmoon/aria/issues/263)) ([428d6cc](https://github.com/poppingmoon/aria/commit/428d6ccf1b5cf8aab530b2857a4b506f9a7be681))
* add option to show drawer button in tab bar ([#262](https://github.com/poppingmoon/aria/issues/262)) ([6ce46b5](https://github.com/poppingmoon/aria/commit/6ce46b56eee4b6c868fec57756c2ac6659dc7b02))
* add users tab to hashtag page ([#266](https://github.com/poppingmoon/aria/issues/266)) ([674500e](https://github.com/poppingmoon/aria/commit/674500e193a38c31f1d6dc3960ace09bf06289bc))
* search with date range ([#270](https://github.com/poppingmoon/aria/issues/270)) ([f767ed4](https://github.com/poppingmoon/aria/commit/f767ed4df335e3bf56c2fb9b0afb6ea1863ebd50))
* add renote as detailed at …

release: 0.11.0 

---

lib/view/widget/as_ui_widget.dart

Wrapped `TextField`s in `AsUiWidget` with `Shortcuts` to disable keyboard shortcuts while typing to the `TextField`s with physical keyboards.

fix: disable shortcuts for inputs of AsUi

---

lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/view/page/settings/appearance_page.dart
lib/view/widget/reaction_button.dart
lib/view/widget/reaction_effect.dart
lib/view/widget/reactions_viewer.dart

Added animation to `ReactionsViewer` when new reactions are received.
https://github.com/poppingmoon/aria/assets/63451158/f1d950bf-e3aa-4826-b0be-d8ce0001ba9f

feat: add animation for reaction update

---

lib/provider/notes_notifier_provider.dart
lib/provider/notes_notifier_provider.g.dart
lib/util/future_with_dialog.dart
lib/util/get_note_action.dart
lib/view/widget/emoji_sheet.dart
lib/view/widget/note_footer.dart
lib/view/widget/poll_widget.dart
lib/view/widget/reaction_button.dart
lib/view/widget/renote_sheet.dart

Changed not to show `CircularProgressIndicator` when adding reactions.

feat: do not show overlay for reaction

---

pubspec.lock
pubspec.yaml
rust/Cargo.lock
rust/Cargo.toml

* add an option to hide new notes popup ([#277](https://github.com/poppingmoon/aria/issues/277)) ([73df855](https://github.com/poppingmoon/aria/commit/73df855d5a1dc8925f2c1f459699910d5401c932))
* add animation for reaction update ([#282](https://github.com/poppingmoon/aria/issues/282)) ([b8b6442](https://github.com/poppingmoon/aria/commit/b8b644254dcef0b6cb16bbaaef6e63333981843f))
* add header to note and user menu ([#286](https://github.com/poppingmoon/aria/issues/286)) ([461808c](https://github.com/poppingmoon/aria/commit/461808c10fd92a4a8da6a6345e61c24fa3ed0a93))
* do not show overlay for reaction ([#283](https://github.com/poppingmoon/aria/issues/283)) ([b9cbd74](https://github.com/poppingmoon/aria/commit/b9cbd74a63706a6f15ff2a4695322d64ed347bb6))
* use inputted host to open …

release: 0.12.0

---

pubspec.lock
pubspec.yaml

* add users tab to list page ([#288](https://github.com/poppingmoon/aria/issues/288)) ([92a04f9](https://github.com/poppingmoon/aria/commit/92a04f92ea910be90aebbc22656b5546ed0504d2)) 
* do not show reaction effect from previous page ([#289](https://github.com/poppingmoon/aria/issues/289)) ([7a84e25](https://github.com/poppingmoon/aria/commit/7a84e25b000145ee0b103e9a3de67f3abd2ff89c))

release: 0.13.0

---

pubspec.yaml

release: 0.13.2

---

lib/extension/notes_create_request_extension.dart
lib/view/dialog/clip_dialog.dart
lib/view/dialog/list_dialog.dart
lib/view/page/avatar_decorations_page.dart
lib/view/page/list/lists_page.dart
lib/view/page/settings/note_display_page.dart
lib/view/widget/clip_preview.dart
pubspec.lock
pubspec.yaml
test_util/dummy_note.dart

This fixes an issue where "Edit note" button does not appear on Sharkey.

fix: make policies nullable

---

ios/Podfile.lock
ios/Runner/Info.plist
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
macos/Runner/Release.entitlements
pubspec.lock
pubspec.yaml

* remove const from `GeneralSettingsNavigation` ([#303](https://github.com/poppingmoon/aria/issues/303)) ([ac7fe41](https://github.com/poppingmoon/aria/commit/ac7fe4159b8c75587cd89b633db857a49262e53f))

release: 0.13.4

---

lib/repository/miauth_repository.dart

Removed callback URL of MiAuth for desktop platforms.

fix: remove MiAuth callback for unsupported platforms

---

lib/model/account_settings.dart
lib/model/account_settings.freezed.dart
lib/model/account_settings.g.dart
lib/provider/account_settings_notifier_provider.dart
lib/provider/account_settings_notifier_provider.g.dart
lib/provider/check_word_mute_provider.dart
lib/provider/muted_words_notifier_provider.dart
lib/provider/muted_words_notifier_provider.g.dart
lib/view/page/settings/mute_block_page.dart
lib/view/widget/muted_words_editor.dart
pubspec.lock
pubspec.yaml
test/provider/check_word_mute_provider_test.dart

Added `mutedWords` and `hardMutedWords` fields to `AccountSettings` to save word mutes locally.

fix: cache muted words 

---

lib/main.dart

Removed default scroll bars for desktop platforms.

fix: hide scroll bar

---

lib/provider/api/timeline_notes_after_note_notifier_provider.dart
lib/provider/api/timeline_notes_after_note_notifier_provider.g.dart
lib/view/page/drive_page.dart
lib/view/widget/follow_requests_list_view.dart
lib/view/widget/notifications_list_view.dart
lib/view/widget/paginated_list_view.dart
lib/view/widget/timeline_list_view.dart

fix: disable pull to refresh if next notes exist

---

pubspec.lock
pubspec.yaml

* cache muted words  ([#310](https://github.com/poppingmoon/aria/issues/310)) ([5618a22](https://github.com/poppingmoon/aria/commit/5618a22d1bec303a92d76c250d170ddb9973b485))
* disable pull to refresh if next notes exist ([#315](https://github.com/poppingmoon/aria/issues/315)) ([c0e133d](https://github.com/poppingmoon/aria/commit/c0e133dde2e1bba989120e66a8a994943bccfcff))
* do not add account if failed to save token ([#308](https://github.com/poppingmoon/aria/issues/308)) ([f8b91e7](https://github.com/poppingmoon/aria/commit/f8b91e71239263eebcd2f6232fc3fbd9758ee63c))
* hide scroll bar ([#314](https://github.com/poppingmoon/aria/issues/314)) ([2fbdbae](https://github.com/poppingmoon/aria/commit/2fbdbae34c545dc6543acad05d17ee0c21057ebf))
* remove MiAuth callback for unsupported platforms …

release: 0.13.5

---

lib/view/widget/note_sheet.dart

fix: edit target note of renote

---

pubspec.yaml

* always update tab index ([#322](https://github.com/poppingmoon/aria/issues/322)) ([64e4029](https://github.com/poppingmoon/aria/commit/64e40293e039f58d6186e6325467dc45c93ecfd3))

release: 0.13.7

---

lib/view/dialog/clip_dialog.dart
lib/view/dialog/list_dialog.dart
lib/view/page/avatar_decorations_page.dart
lib/view/page/list/lists_page.dart
lib/view/page/settings/profile_page.dart
lib/view/page/user/user_home.dart
lib/view/widget/clip_preview.dart
lib/view/widget/user_info.dart
pubspec.lock
pubspec.yaml

Support mutual links in profiles for misskey.io.
ref: `https://github.com/MisskeyIO/misskey/pull/684`

feat: mutual links

---

lib/view/widget/mfm/spin.dart

Corrected rotation direction of spin.x and spin.y.

fix: fix rotation direction of mfm spin

---

lib/view/widget/mfm/bounce.dart
lib/view/widget/mfm/jelly.dart
lib/view/widget/mfm/jump.dart
lib/view/widget/mfm/rainbow.dart
lib/view/widget/mfm/shake.dart
lib/view/widget/mfm/spin.dart
lib/view/widget/mfm/tada.dart
lib/view/widget/mfm/twitch.dart

ref: `https://github.com/misskey-dev/misskey/pull/14200`

feat: support mfm negative delay

---

lib/model/id.dart
lib/provider/api/timeline_notes_notifier_provider.dart
lib/provider/api/timeline_notes_notifier_provider.g.dart
pubspec.lock
pubspec.yaml

Added partial support for Iceshrimp-style pagination of antenna notes.

feat: support pagination of antenna notes

---

lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/view/page/settings/behavior_page.dart
lib/view/widget/media_card.dart

Added an option to show a confirmation dialog before opening sensitive files.
ref: `https://github.com/misskey-dev/misskey/pull/14115`

feat: confirm when revealing sensitive media

---

lib/view/widget/play_widget.dart

fix: maintain state of Play widget

---

lib/provider/api/id_gen_method_provider.dart
lib/provider/api/id_gen_method_provider.g.dart
lib/provider/api/play_notifier_provider.dart
lib/provider/api/play_notifier_provider.g.dart
lib/view/page/play/play_edit_page.dart
lib/view/widget/play_preview.dart

As of Misskey 2024.8.0, visibility of Play became available over the endpoints. This PR supports the change.
ref: `https://github.com/misskey-dev/misskey/pull/14384`

fix: preserve Play visibility

---

pubspec.yaml

* remove colorFilter for Impeller ([#360](https://github.com/poppingmoon/aria/issues/360)) ([b36fde2](https://github.com/poppingmoon/aria/commit/b36fde265effdda55d57162f851f65ba16987cec))

release: 0.14.1

---

pubspec.yaml

* delete draft text on reply ([#364](https://github.com/poppingmoon/aria/issues/364)) ([bae53db](https://github.com/poppingmoon/aria/commit/bae53dbe0431f4730b4b42446a58bc8db0b4eeec))

release: 0.14.2

---

pubspec.lock
pubspec.yaml

* clear composing range when inserting text ([#366](https://github.com/poppingmoon/aria/issues/366)) ([a1e856c](https://github.com/poppingmoon/aria/commit/a1e856cdfaa41c1ed5c52c18888b5b14a709fddb))

release: 0.14.3

---

lib/repository/miauth_repository.dart
lib/util/launch_url.dart
lib/view/page/login_page.dart

Changed to open MiAuth with in-app WebView on iOS.

fix: open MiAuth in app if iOS

---

lib/provider/api/page_provider.dart
lib/provider/api/page_provider.g.dart
lib/view/page/page/page_page.dart
pubspec.lock
pubspec.yaml

Changed to display pages following `alignCenter` and `font` properties.

fix: apply align and font for page

---

lib/constant/shortcuts.dart
lib/view/widget/post_form.dart

When pasting a url to the post form, wrap it with link mfm(`[]()`) if a text range is selected.

feat: wrap link when pasting url

---

lib/view/page/user/user_page.dart

Changed confetti animation for birthday users to be explosive and short.

feat: enhance confetti

---

lib/view/dialog/text_field_dialog.dart
lib/view/page/settings/tab_settings_page.dart
pubspec.lock
pubspec.yaml

Added suggestions for endpoints to support inputting them for custom tabs.

feat: add autocomplete for endpoints

---

pubspec.lock
pubspec.yaml

fix: allow period in mention

---

lib/provider/receive_sharing_intent_provider.dart
lib/provider/receive_sharing_intent_provider.g.dart
lib/provider/share_notifier_provider.dart
lib/provider/share_notifier_provider.g.dart
lib/router/router.dart
lib/router/router.g.dart

Moved logic that determines where to redirect when files are shared to simplify the redirect callback of the router.

refactor: move redirect logic to notifier

---

lib/view/widget/mfm/code.dart

Added a button to copy the content of the code block.

feat: add copy button on code block

---

lib/provider/api/children_notes_notifier_provider.dart
lib/provider/api/children_notes_notifier_provider.g.dart
pubspec.lock
pubspec.yaml

fix: set depth of children notes to 1

---

android/app/src/main/AndroidManifest.xml

fix: remove intent filter for view files action

---

lib/provider/api/i_notifier_provider.dart
lib/provider/api/i_notifier_provider.g.dart
lib/view/page/settings/profile_page.dart
lib/view/page/user/user_home.dart
lib/view/widget/notification_widget.dart
pubspec.lock
pubspec.yaml

Added support for the followed message feature.
ref: `https://github.com/misskey-dev/misskey/pull/14430`

feat: support followed message

---

lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_widget.dart
lib/view/widget/poll_widget.dart
lib/view/widget/sub_note_content.dart

Fixed an issue where changing the font size and line heights in the note display page were not reflected in the preview.

fix: apply note display settings immediately

---

lib/view/page/page/page_page.dart
lib/view/widget/media_card.dart
lib/view/widget/media_list.dart
lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_widget.dart
lib/view/widget/poll_widget.dart
lib/view/widget/renote_header.dart
lib/view/widget/sub_note_content.dart
lib/view/widget/url_preview.dart

Removed horizontal margin around `MediaCard`, `UrlPreview`, and `PollWidget`.

fix: tweak spaces inside NoteWidget

---

lib/view/widget/note_footer.dart
lib/view/widget/renote_sheet.dart

Change the color of the renote button if
- the button is in a renote by the user
- the user renoted by using the button
Fix #391

feat: highlight renote icon

---

lib/view/widget/note_footer.dart

Fixed an issue where the renote buttons are highlighted for all renotes instead of only the renotes made by the user.
Follow up for #422

fix: only highlight my renote

---

pubspec.lock
pubspec.yaml

fix: use forked version of highlighting

---

lib/view/page/announcements_page.dart
lib/view/page/channel/channels_search.dart
lib/view/page/search/search_users.dart
lib/view/page/user/user_home.dart
lib/view/page/user/user_notes.dart
lib/view/widget/timeline_list_view.dart

Changed to hide buttons on top of the notes created by users when scrolling down and show them when scrolling up.

feat: float header buttons in UserNotes

---

.github/workflows/build.yml

ci: use authentication key

---

pubspec.yaml

release: 1.0.0-beta.3

---

.github/workflows/build.yml
pubspec.yaml

release: 1.0.0-beta.4

---

android/app/src/main/AndroidManifest.xml

fix: remove https intent filter

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/model/account_settings.dart
lib/model/account_settings.freezed.dart
lib/model/account_settings.g.dart
lib/model/mfm_config.dart
lib/model/mfm_config.freezed.dart
lib/provider/account_settings_notifier_provider.dart
lib/provider/muted_emojis_notifier_provider.dart
lib/provider/muted_emojis_notifier_provider.g.dart
lib/view/page/settings/mute_block_page.dart
lib/view/widget/custom_emoji.dart
lib/view/widget/emoji_picker.dart
lib/view/widget/emoji_sheet.dart
lib/view/widget/emoji_widget.dart
lib/view/widget/mfm.dart
lib/view/widget/mfm/mfm_builder.dart
lib/view/widget/unicode_emoji.dart

Added a feature to mute emojis. 
Muted emojis are replaced with a dummy image.

feat: emoji mute

---

lib/view/page/settings/accounts_page.dart
lib/view/page/settings/tabs_page.dart

Fixed an issue where reordering of tabs and accounts is not working.

fix: offset reorder index

---

lib/view/widget/note_footer.dart
lib/view/widget/reaction_users_sheet.dart

Added some space around emojis in `ReactionUsersSheet` for better accessibility.

fix: change style of emojis in ReactionUsersSheet

---

lib/view/widget/player_embed.dart
lib/view/widget/twitter_embed.dart

Fixed an issue where embeds of some websites redirect to different sites.

fix: disable redirect in embed

---

lib/view/widget/cw_button.dart
lib/view/widget/follow_requests_list_view.dart
lib/view/widget/note_widget.dart
lib/view/widget/notifications_list_view.dart
lib/view/widget/poll_widget.dart
lib/view/widget/post_form.dart
lib/view/widget/sub_note_content.dart
lib/view/widget/timeline_list_view.dart
lib/view/widget/url_preview.dart

Made buttons in notes smaller and monotonal.

fix: change style of cw button

---

lib/provider/streaming/incoming_message_provider.dart
lib/provider/streaming/incoming_message_provider.g.dart
lib/util/compress_image.dart

Changed to call `debugPrint` only on debug build.

chore: print log only when debug mode

---

lib/view/page/announcements_page.dart
lib/view/widget/notification_widget.dart
pubspec.lock
pubspec.yaml

Added support for `note:grouped` notification from CherryPick.
ref: https://github.com/kokonect-link/cherrypick/commit/e9d7399f1235807f115b56cbae65d0b45ff332a6
Fix #486

feat: support grouped note notification

---

lib/view/widget/error_message.dart

Added error messages for `CREDENTIAL_REQUIRED` and `SIGNIN_REQUIRED`.
ref: `https://github.com/misskey-dev/misskey/pull/14799`

feat: add message for signin required exception

---

crowdin.yml

Changed app descriptions for stores to be available on Crowdin for translation.

build: add store metadata files to Crowdin

---

lib/hook/on_window_move_hook.dart
lib/hook/on_window_moved_hook.dart
lib/hook/on_window_resize_hook.dart
lib/hook/on_window_resized_hook.dart
lib/main.dart
lib/provider/window_position_repository_provider.dart
lib/provider/window_position_repository_provider.g.dart
lib/provider/window_size_repository_provider.dart
lib/provider/window_size_repository_provider.g.dart
lib/repository/window_position_repository.dart
lib/repository/window_size_repository.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

On desktop platforms, save the window's size and position when it resizes or moves. When the app starts, these settings are loaded and the window will be resized.

feat: preserve window size and position

---

lib/provider/cache_manager_provider.dart
lib/provider/cache_manager_provider.g.dart
pubspec.lock
pubspec.yaml

Changed base directory of cache manager from temporary directory to application cache directory.

fix: use cache directory for cache manager

---

ios/Localizable.xcstrings
lib/main.dart
lib/view/page/role_page.dart
lib/view/widget/notification_widget.dart
script/gen_localizable.dart

Added support for the push notification for role assigned.
ref: poppingmoon/misskey-web-push-proxy@edd79971d7bb64de3fffd49f58217130302bfca0

feat: support role assigned push notification

---

lib/view/dialog/image_gallery_dialog.dart

Changed `ImageGalleryDialog` to show a thumbnail image instead of the actual image until it is loaded.

feat: show thumbnail while loading raw image

---

lib/view/widget/mfm.dart
pubspec.lock
pubspec.yaml

fix: support speak as cat

---

.github/workflows/build.yml

Added steps to publish App Bundle to open test on Google Play.

ci: upload App Bundle to Google Play

---

lib/view/page/user/user_home.dart
lib/view/widget/post_form.dart

Added blur to buttons at the bottom left of the post form to indicate that they are scrollable.

fix: add blur to post form footer if overflowed

---

lib/gen/assets.gen.dart
lib/view/page/settings/mute_block_page.dart
lib/view/widget/emoji_sheet.dart
lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_header.dart
lib/view/widget/note_sheet.dart
lib/view/widget/post_form.dart
lib/view/widget/renote_header.dart
lib/view/widget/renote_sheet.dart
lib/view/widget/role_preview.dart
lib/view/widget/user_sheet.dart
pubspec.lock
pubspec.yaml

Replaced some icons with Material Symbols.

feat: use material symbols 

---

android/app/src/main/kotlin/com/poppingmoon/aria/EmbeddedDistributor.kt
lib/main.dart
lib/provider/shared_preferences_provider.dart
lib/provider/shared_preferences_provider.g.dart
lib/repository/window_position_repository.dart
lib/repository/window_size_repository.dart
pubspec.lock
pubspec.yaml
test_util/fake_shared_preferences.dart

Added migration from `SharedPreferences` to `SharedPreferencesWithCache`.
ref: https://pub.dev/packages/shared_preferences#migration-and-prefixes

feat: migrate to SharedPreferencesWithCache

---

lib/view/widget/note_detailed_widget.dart
lib/view/widget/note_header.dart
lib/view/widget/note_widget.dart
test/view/widget/note_widget_test.dart

Extracted contents of `NoteWidget` and `NoteDetailedWidget` for better maintainability.

refactor: split note content to widget

---

lib/model/general_settings.dart
lib/model/general_settings.freezed.dart
lib/model/general_settings.g.dart
lib/provider/general_settings_notifier_provider.dart
lib/provider/general_settings_notifier_provider.g.dart
lib/view/page/settings/note_display_page.dart
lib/view/widget/mfm.dart
lib/view/widget/note_footer.dart
lib/view/widget/note_header.dart
lib/view/widget/note_simple_widget.dart
lib/view/widget/note_sub_widget.dart
lib/view/widget/note_widget.dart
lib/view/widget/sub_note_content.dart
lib/view/widget/timeline_list_view.dart
lib/view/widget/timeline_note.dart
test/view/widget/note_widget_test.dart
test/view/widget/timeline_list_view_test.dart

Added an option to show a gap between notes in timelines.

feat: show gap between notes

---

lib/view/page/login_page.dart

#493 added validation for `meta` in order to check if the server supports MiAuth. This causes loading when tapping the sign-in button since it fetches the data from the server. To reduce the lag, changed the process to use the server data from joinmisskey if available.

fix: use joinmisskey data to check miauth availability

---

snap/snapcraft.yaml

Fixed an issue where the file picker does not appear on the snap version.

build: add zenity to stage-packages

---

lib/provider/api/user_notifier_provider.dart
lib/provider/api/user_notifier_provider.g.dart
lib/view/dialog/mute_dialog.dart
lib/view/page/settings/blocked_users_page.dart
lib/view/page/settings/muted_users_page.dart
lib/view/page/settings/renote_muted_users_page.dart
lib/view/widget/duration_widget.dart
lib/view/widget/poll_editor.dart
lib/view/widget/user_sheet.dart

Added a dialog that asks users how long they want to mute an account.

feat: temporary mute

---

lib/view/widget/note_detailed_widget.dart
lib/view/widget/post_form.dart

Changed to update children notes in the note page when the user posted a reply or quote to it.

feat: update children notes on reply or quote

---

lib/view/page/drive_page.dart
lib/view/page/user/user_home.dart
lib/view/widget/mfm.dart
lib/view/widget/note_header.dart
lib/view/widget/timeline_header.dart

fix: disable bidirectional isolates for Linux

---

lib/i18n/aria/aria.i18n.yaml
lib/i18n/strings.g.dart
lib/i18n/strings_en_US.g.dart
lib/provider/accounts_notifier_provider.dart
lib/provider/accounts_notifier_provider.g.dart
lib/provider/miauth_notifier_provider.dart
lib/provider/miauth_notifier_provider.g.dart
lib/provider/share_notifier_provider.dart
lib/provider/share_notifier_provider.g.dart
lib/repository/miauth_repository.dart
lib/router/router.dart
lib/router/router.g.dart
lib/util/copy_text.dart
lib/util/future_with_dialog.dart
lib/util/show_toast.dart
lib/view/page/authenticate_page.dart
lib/view/page/settings/import_export_page.dart
lib/view/page/token_login_page.dart

Changed to show a toast message that indicates sign in has been completed successfully.
This will be shown when a user approves MiAuth on the browser and is redirected back to the app or taps "Authenticated". It will also appear when signed in with an access token.

feat: show toast when signed in

---

.github/workflows/ci.yml
lib/view/widget/media_list.dart

Added minimum height constraints for `MediaList` to prevent buttons in `MediaCard` from getting overlapped.
Follow up for #567

fix: add constraint for MediaList

---

lib/provider/notes_notifier_provider.dart
lib/provider/notes_notifier_provider.g.dart
lib/util/append_content_warning.dart
pubspec.lock
pubspec.yaml

ref: https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/876
Fix #581

feat: support mandatory cw

---

macos/Runner/DebugProfile.entitlements
macos/Runner/Release.entitlements
pubspec.lock
pubspec.yaml

* support mandatory cw ([#583](https://github.com/poppingmoon/aria/issues/583)) ([df5bdee](https://github.com/poppingmoon/aria/commit/df5bdee250db8064f3102dc33e4bf1218d2ea343))
* use separate server url for api call ([#582](https://github.com/poppingmoon/aria/issues/582)) ([0307087](https://github.com/poppingmoon/aria/commit/030708713633197a1aa1eaedbc631cd21b963f2e))       
* use UnifiedPush connector 3 ([#585](https://github.com/poppingmoon/aria/issues/585)) ([d76c72d](https://github.com/poppingmoon/aria/commit/d76c72d2b46264f75da7c493c48e533a86b7c8dd))
* remove BlurHash from loading image  ([#580](https://github.com/poppingmoon/aria/issues/580)) ([7c0ca7e](https://github.com/poppingmoon/aria/commit/7c0ca7eb36b086a7db126c24b707d40f8a231d3d))        
* change layout of MediaList with 3 …

release: 1.0.0

---

android/app/build.gradle

fix: remove DependencyInfoBlock

---

lib/view/page/timelines_page.dart

Improved handling of tab index to update when the tab is swiped halfway.

fix: change tab index in the middle of transition

---

lib/view/widget/username_widget.dart

Fixed an issue where emoji mute is not applied to the emojis in the username.

fix: add author to UsernameWidget

---

lib/provider/post_notifier_provider.dart
lib/provider/post_notifier_provider.g.dart
pubspec.lock
pubspec.yaml

ref: `https://github.com/kokonect-link/cherrypick/pull/601`

fix: respect localOnly for note scheduling

---

lib/view/widget/gallery_post_preview.dart
lib/view/widget/image_widget.dart
lib/view/widget/media_card.dart

Set the `optimizationMode` parameter of `BlurHash` to `BlurHashOptimizationMode.approximation` for better performance.
ref: https://github.com/fluttercommunity/flutter_blurhash/tree/c5cdec4#optimization-modes

perf: set optimization mode of BlurHash

---

lib/extension/string_extension.dart
lib/provider/api/search_notes_notifier_provider.dart
lib/provider/api/search_notes_notifier_provider.g.dart
lib/provider/api/search_users_notifier_provider.dart
lib/provider/api/search_users_notifier_provider.g.dart
lib/provider/custom_emoji_index_provider.dart
lib/provider/search_custom_emojis_provider.dart
lib/provider/search_custom_emojis_provider.g.dart
lib/provider/search_unicode_emojis_provider.dart
lib/provider/search_unicode_emojis_provider.g.dart
lib/provider/searched_queries_notifier_provider.dart
lib/provider/searched_queries_notifier_provider.g.dart
lib/util/safe_to_katakana.dart
lib/view/dialog/text_field_dialog.dart
lib/view/page/search/search_notes.dart
lib/view/page/search/search_page.dart
lib/view/page/search/search_users.dart
lib/view/widget/misskey_server_autocomplete.dart

Changed the style of the search page and added an options view to the search bar, which shows previously searched queries.

feat: show search history

---

lib/view/widget/note_footer.dart
pubspec.lock
pubspec.yaml

fix: support isRenoted

---

lib/provider/accounts_notifier_provider.dart
lib/provider/accounts_notifier_provider.g.dart

Fixed an issue where an account was not removed when launching the app after logging out.

fix: persist account removal

---

lib/provider/api/search_users_by_username_provider.dart
lib/provider/api/search_users_by_username_provider.g.dart
lib/view/dialog/user_select_dialog.dart
lib/view/widget/mfm_keyboard.dart
test/view/widget/mfm_keyboard_test.dart

Added a delay before searching users and hashtags on the mfm keyboard.

fix: debounce user and hashtag search in mfm keyboard

---

lib/provider/notes_notifier_provider.dart
lib/provider/notes_notifier_provider.g.dart
lib/view/widget/deleted_note_widget.dart
lib/view/widget/deleted_renote_widget.dart
lib/view/widget/note_simple_widget.dart
lib/view/widget/note_sub_widget.dart

Fixed an issue where the quote target is displayed as a deleted note if the quote is a reply.
Follow up for #695

fix: load omitted note

---

.github/workflows/ci.yml
lib/provider/api/clips_notifier_provider.dart
lib/provider/api/clips_notifier_provider.g.dart
lib/view/dialog/clip_dialog.dart
lib/view/page/clip_page.dart
lib/view/page/clips_page.dart
pubspec.lock
pubspec.yaml

Added support for pagination for `clips/list` endpoint, which was added in [misskey-dev/misskey#16434](https://redirect.github.com/misskey-dev/misskey/pull/16434).

fix: support pagination for clips

---

.github/workflows/build.yml

Added a step to check the version code of the built APKs.

ci: check version codes

---

lib/view/widget/announcement_widget.dart

Changed to show both the created date and the updated date of announcements.

fix: show update date of announcement

---

lib/provider/recently_used_emojis_notifier_provider.dart
lib/provider/recently_used_emojis_notifier_provider.g.dart
lib/view/page/settings/pinned_emojis_editor_page.dart
lib/view/widget/emoji_sheet.dart

Added a feature to remove a specific emoji from recently used emojis.

feat: remove emoji history
